### ISSUE TITLE
New Cluster creation deletes /etc/kubernetes directory.

### ISSUE THREAD

**Issue by jgreat** [rancher/terraform-provider-rke#101]
https://github.com/yamamoto-febc/terraform-provider-rke/blob/495216b78710c22cc511cd850679ae1ad75be948/rke/resource_rke_cluster.go#L88

Looks like when a new cluster is created a clusterRemove is run. This should not be necessary.  This is deleting configuration files that might be bootstrapped ahead of time.  This breaks Rancher's hardening guide instructions https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.1/

**Comment by yamamoto-febc** [comment]
Hi @jayed,

Thank you for your report.
It was an error when re-creating a cluster for the same node without this process until some time ago.
If there is no problem, we will try to remove this process.

**Comment by tlvenn** [comment]
Got bitten by this as well with our encryption yaml being wiped in the process. Would be great to address this asap. Thanks a lot in advance.

**Comment by tlvenn** [comment]
This is also borderline dangerous, I have no idea how it happened but I got a k8s cluster wiped out clean because of this. Imho, the provider should not call delete on behalf of the user unless explicitly asked because the resource is gone.

**Comment by tlvenn** [comment]
@yamamoto-febc any chance to look into this ? It would be safer if the provider would not invoke `clusterRemove` on its own. Thanks in advance.

**Comment by yamamoto-febc** [comment]
@tlvenn sorry for delay.  

I think we should remove the destroy. But now I don't have time to verify it. Please wait for a while. I'd like to verify this on this month.

**Comment by tlvenn** [comment]
Thanks !

**Comment by ajchiarello** [comment]
Does anyone know a workaround for this that allows an installation with encrypted etcd?

**Comment by tlvenn** [comment]
Yes, don't use `/etc/kubernetes` ;)

```
services_kube_api {
    extra_args = {
      encryption-provider-config = "/opt/kubernetes/encryption.yml"
    }
     
     # We have to use /opt/kubernetes instead of /etc/kubernetes
     # See https://github.com/yamamoto-febc/terraform-provider-rke/issues/101
     extra_binds = [
       "/opt/kubernetes:/opt/kubernetes"
     ]
  }
```

**Comment by ajchiarello** [comment]
@tlvenn I tried that, and I just get an error:

> error opening encryption provider configuration file "/opt/kubernetes/encryption.yaml": open /opt/kubernetes/encryption.yaml: no such file or directory]

I set up the extra bind and mapped to the new folder - was there anything else you needed to do to make that work?

**Comment by tlvenn** [comment]
you need to provision that file on the host ;)

**Comment by ajchiarello** [comment]
Yes, of course. I've been provisioning the file on the host all along.

**Comment by rawmind0** [comment]
Please, reopne issue if needed.
