### ISSUE TITLE
Help with re-working dynamic nodes

### ISSUE THREAD

**Issue by jbmcfarlin31** [rancher/terraform-provider-rke#102]
Before terraform v.0.12 was released, I had a really good way of being able to deploy RKE nodes dynamically. Now that I have begun my dive into the latest terraform, I am unsure how to proceed with the new way of creating dynamic nodes... I have looked at the example given on this repo, but I am having a hard time translating between my version and the new "way".

I tried translating my way into the new `variables` block, however that error'd out saying things like:
```
Error: Unsupported argument

  on rke.tf line 20, in variable "nodes":
  20:   count = var.NODE_COUNT

An argument named "count" is not expected here.


Error: Variables not allowed

  on rke.tf line 27, in variable "nodes":
  27:       address = azurestack_public_ip.vmpip.*.ip_address[count.index]

Variables may not be used here.
```
 

Here is my code:
```
# locals to allow us to control which nodes get assigned manager roles vs. controlplane and workers
locals {
  mgr_roles    = ["controlplane","etcd"]
  worker_roles = ["worker"]
}

# This is currently the way we are dynamically provisioning nodes. 
# This is used in a CI/CD process, so we have a script and pass in the number of manager nodes
# to create and the number of total nodes for the entire cluster 
# (ex. deploy.sh --deployment-name mytest --managers 3 --nodes 5, which would create all resources using the "mytest" prefix, and it would yield a k8s cluster with 5 nodes total and 3 of those nodes being managers
# data rke_node_parameter "nodes" {
#   count    = "${var.NODE_COUNT}"
#   address = "${azurestack_public_ip.vmpip.*.ip_address[count.index]}"
#   user    = "myuser"
#   role = "${split(",", count.index < var.nbr_managers ? join(",", local.mgr_roles) : join(",", local.worker_roles))}"
#   ssh_key = "${file("path/to/sshkey")}"
# }

# How does the above ^^^^ translate into here???
variable "nodes" {
  type = list(object({
    address = string,
    user    = string,
  }))
  default = [
    {
      address = "192.2.0.1"
      user    = "ubuntu"
    },
    {
      address = "192.2.0.2"
      user    = "ubuntu"
    },
  ]
}

resource rke_cluster "cluster" {
  depends_on = ["azurestack_public_ip.vmpip", "azurestack_virtual_machine.vm"]

  # This is how I am referencing the old dynamic way...
  #nodes_conf = ["${data.rke_node_parameter.nodes.*.json}"]

  # Instead of defining a variable block, could I handle the dynamic logic in this piece here using the "azurestack_public_ip...[count.index]" syntax?
  dynamic nodes {
    for_each = var.nodes
    content {
      address = nodes.value.address
      user    = nodes.value.user
      role    = split(",", count.index < var.nbr_managers ? join(",", local.mgr_roles) : join(",", local.worker_roles))
      ssh_key = file("path/to/sshkey")
    }
  }

  ignore_docker_version = true
  cluster_name = "${var.deployment_name}-cluster"

  # Kubernetes version
  kubernetes_version = "v1.13.5-rancher1-2"
}
```

**Comment by yamamoto-febc** [comment]
Hi @jbmcfarlin31, 

I think that you probably don't need to use `var.nodes`.
We can use resources directly on dynamic block as follows.

```hcl
# locals to allow us to control which nodes get assigned manager roles vs. controlplane and workers
locals {
  mgr_roles    = ["controlplane","etcd"]
  worker_roles = ["worker"]
}

resource rke_cluster "cluster" {
  depends_on = ["azurestack_public_ip.vmpip", "azurestack_virtual_machine.vm"]

  dynamic nodes {
    for_each = azurestack_public_ip.vmpip.*
    content {
      address = nodes.value.ip_address
      user    = "myuser"
      role    = split(",", nodes.key < var.nbr_managers ? join(",", local.mgr_roles) : join(",", local.worker_roles))
      ssh_key = file("path/to/sshkey")
    }
  }

  ignore_docker_version = true
  cluster_name = "${var.deployment_name}-cluster"

  # Kubernetes version
  kubernetes_version = "v1.13.5-rancher1-2"
}
```

ref: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks

Please try it.

**Comment by jbmcfarlin31** [comment]
@yamamoto-febc thank you for the reply and example, it is much appreciated! I will give this try as soon as possible. Currently, the terraform azure stack provider is having issues with the release of stacks latest build... so it might be a few before I can try.

**Comment by sebastien-prudhomme** [comment]
@jbmcfarlin31 i'm sharing my OpenStack setup:

```tf
resource "rke_cluster" "main" {
  dynamic "nodes" {
    for_each = openstack_networking_port_v2.main[*].all_fixed_ips[0]
    iterator = address

    content {
      address           = address.value
      role              = address.key < var.replicas_master ? ["controlplane", "etcd"] : ["worker"]
      hostname_override = openstack_compute_instance_v2.main[address.key].name
      user              = var.user
    }
  }
  
  ...
}
```

It's similar to previous answer, i'm just giving a name to the iterator for readabilitity.

What you can also do is remove the split/join trick as TF 0.12 now allow lists in the ternary operator.

**Comment by jbmcfarlin31** [comment]
@sebastien-prudhomme thank you for sharing! I am currently waiting for the azure stack provider to get patched with the latest build release from azure stack.. so I cannot test anything at the moment. 

I did have questions about the split/join trick and what you are doing for the roles part of the RKE setup.

When you do this:
`role              = address.key < var.replicas_master ? ["controlplane", "etcd"] : ["worker"]`
It is essentially the same as my:
`role    = split(",", count.index < var.nbr_managers ? join(",", local.mgr_roles) : join(",", local.worker_roles))`

So I am guessing that the `address.key` is what "node" the iterator is on in your nodes list, and the `var.replicas_master` contains how many master nodes the cluster is going to have. Then based on the logic - if the `address.key` is less then say 3 nodes it will get assigned k8s master roles, and if it is greater, it will get assigned worker roles in a 5 node cluster setup. Is that correct?

**Comment by sebastien-prudhomme** [comment]
@jbmcfarlin31 Yes this is correct, if i apply the same thing to your file, it should be something like this:

```tf
role = nodes.key < var.nbr_managers ? local.mgr_roles : local.worker_roles
```

**Comment by jbmcfarlin31** [comment]
@sebastien-prudhomme awesome! Thank you for that. I will give this a try when the azs provider is fixed. I was wanting to rewrite my terraform code to be more syntactically correct for v0.12, so this is great. Much appreciated.

**Comment by ulm0** [comment]
I use the code bellow to provision the nodes roles:

```hcl
...
  dynamic nodes {
    for_each = [for ip in local.node_ips : {
      ip_addr = ip
    }]

    content {
      address  = nodes.value.ip_addr
      role     = index(local.node_ips, nodes.value.ip_addr) + 1 > var.cpn ? ["worker"] : ["controlplane", "etcd"]
      ssh_cert = data.external.ssh_public_cert.result["signed_key"]
      ssh_key  = tls_private_key.ssh.private_key_pem
      user     = var.vm_user
    }
  }
```

where `var.cpn` stands for "control plane nodes", so i can pass 1, 3, 5 or 7

some more context:

```hcl
locals {
  ...
  node_ips   =  values(var.nodes)
  ...
}
```

`var.nodes` is a map containing `{ node_name = "node_ip" }`, i'm creating all of this infrastructure on vSphere

**Comment by caleno** [comment]
One thing that doesn't seem to work with dynamic nodes is using ssh_agent_auth, this has to be set "globally" 

E.g 

*Dose not work*

```
resource "rke_cluster" "rancher_server" {
  depends_on = [null_resource.wait_for_docker]

  dynamic nodes {
    for_each = aws_instance.rancher_master
    content {
      address          = nodes.value.public_ip
      internal_address = nodes.value.private_ip
      user             = var.instance_ssh_user
      role             = ["controlplane", "etcd"]
      #ssh_key          = file("${path.module}/secret_files/id_rsa")
      ssh_agent_auth   = true
      #ssh_key          = tls_private_key.ssh.private_key_pem
    }
  }
...
```
This fails with warning: 

> [warning] Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [x.x.x.x:22] using SSH. Using encrypted private keys is only supported using ssh-agent. Please configure the option `ssh_agent_auth: true` in the configuration file or use --ssh-agent-auth as a parameter when running RKE. This will use the `SSH_AUTH_SOCK` environment variable. Error: Error configuring SSH: ssh: cannot decode encrypted private keys




*Works*

```
resource "rke_cluster" "rancher_server" {
  #depends_on = [null_resource.wait_for_docker]
  ssh_agent_auth   = true

  dynamic nodes {
    for_each = aws_instance.rancher_master
    content {
      address          = nodes.value.public_ip
      internal_address = nodes.value.private_ip
      user             = var.instance_ssh_user
      role             = ["controlplane", "etcd"]
      #ssh_key          = file("${path.module}/secret_files/ida_rsa")
      #ssh_agent_auth   = true
      #ssh_key          = tls_private_key.ssh.private_key_pem
    }
  }
...
```

But maybe it was never meant to work either, I am just pitching in so that others having the same problem knows about this.

**Comment by rawmind0** [comment]
Please, reopne issue if needed.
