### ISSUE TITLE
Kubernetes cluster on VMs with Proxy

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#106]
Hi,

All our cluster nodes are using proxy to connect to internet for downloading things , docker is already configured to pull images , but how can I configure kubernetes at cluster creation time to use the proxy? Is there some environment variable that i need to set?

thanks

**Comment by yamamoto-febc** [comment]
Hi, 

I think that RKE is written in go and seems to support environment variables such as HTTP_PROXY.

I haven't tried it because I don't have a Proxy environment, but it may not work because of the following issues.
https://github.com/rancher/rke/issues/1248

**Comment by jbmcfarlin31** [comment]
@iahmad-khan we use a proxy as well. You need to have no proxy configured to have RKE install and deploy. Once the cluster has been deployed, you can hit your nodes with configuration management to set the proxy env vars again.

**Comment by rawmind0** [comment]
It should work following https://github.com/rancher/rke/issues/1248#issuecomment-544149163

Please, reopen issue if needed.
