### ISSUE TITLE
RKE and node provisioning within same project

### ISSUE THREAD

**Issue by nmeisenzahl** [rancher/terraform-provider-rke#108]
Hi,
this is not a bug report - more a question.
I'm using a single Terraform project to provision my nodes as well as RKE. My nodes are defined in a list variable (worker as well as master nodes) like this:

`variable "worker_hosts_prod" {
  type = list(object({
    address = string,
    name    = string,
  }))
  default = [
    {
      address = "<ip>"
      name    = "<hostname>"
    },
    {
      address = "<ip>"
      name    = "<hostname>"
    },
  ]
}`

Terraform then creates these nodes and run the RKE provider afterward. The RKE resources depends on the nodes to make sure they are ready before the RKE provider runs. 

This works pretty well until you decide to remove a node. Because of "depend on" the node itself will be deleted before the RKE provider runs to remove it from the cluster (which then is of course not possible anymore).
 
Any ideas on how to fix that? Following would be needed:

- when a node is added: Create nodes, then run RKE

- when a node is removed node: run RKE, then delete nodes

The above-mentioned problem seems to be fine for the worker nodes but the master nodes are not removed and keep staying in the cluster (not-ready of course). I'm also not sure about etcd (which runs on the master).

Any ideas?

**Comment by yamamoto-febc** [comment]
Hi, 

For example, how about the following?
https://github.com/yamamoto-febc/terraform-provider-rke/issues/102#issuecomment-512169915

In this example, the rke_cluster resource is directly dependent on child resources such as nodes.
Terraform handles their dependencies well.
(Maybe I don't understand the problem well...)

**Comment by nmeisenzahl** [comment]
Hi,

thanks. I will test this. 

Greets

**Comment by nmeisenzahl** [comment]
Hi,
sorry for my late response. My issue is a different one. 

I'm provision multiple virtual machines resources as well as the RKE resource within the same Terraform project. When I force recreation of one or multiple virtual machines (rebuild them using a new template or something similar, or also a terraform taint) the virtual machine will be rebuilt but the RKE provisioner does not run and does not update/reinstall the new nodes. 

The link between the virtual machine nodes and the RKE resources are missing. The "depends_on" feature is only used to define the order. 

I fixed this issue by linking the virtual machine with the RKE resource. I did this by writing the VM template version into a node label. This will force an RKE resource modification every time the template of a virtual machine changes. Not ideal, but it works for now. 

`labels = {
  templateHash = md5(join(",", ["${data.vsphere_virtual_machine.master.id}", "${data.vsphere_virtual_machine.worker.id}"]))
}`

I don't think there is any solution in Terraform to define dependencies between different resources to force modification/recreation. Maybe you can build an attribute which can be used for this instead using a label (which I did). Just as an idea. Feel free to close this issue.

Greets

**Comment by vitobotta** [comment]
@nmeisenzahl I've had the same problem during my testing.

**Comment by rawmind0** [comment]
@nmeisenzahl , @vitobotta  if nothing is changing on nodes argument, the rke cluster is unable to know that an update is needed. 

@nmeisenzahl  about adding an attribute to force it, should work but the problem would be that you need to update tf file once is done. It's better scope use a label as you did to selectively update.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
