### ISSUE TITLE
not creating kubeconfig file for aws_ec2 example

### ISSUE THREAD

**Issue by fish-finger** [rancher/terraform-provider-rke#111]
Get this area message each time

  on rke.tf line 8, in resource "rke_cluster" "cluster":
   8: resource "rke_cluster" "cluster" {

**Comment by yamamoto-febc** [comment]
Hi @fish-finger 

Thank you for reporting this. 
I'm going to check it.

**Comment by fish-finger** [comment]
I solved the problem,
https://github.com/yamamoto-febc/terraform-provider-rke/blob/master/examples/aws_ec2/aws/nodes.tf

 "curl releases.rancher.com/install-docker/1.12.sh | bash" --> "curl releases.rancher.com/install-docker/1.13.sh | otherwise the docker version is not recognised and it fails to finish the end of the step creating the config file.

Awesome code by the way, makes the entire process much more manageable my friend.

**Comment by ctcampbell** [comment]
I'm also getting this issue when deploying:

```
resource rke_cluster "cluster" {
  nodes {
    address = "ubuntu"
    user    = "user"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = "${file("~/.ssh/id_rsa")}"
  }
  addons_include = [
    "https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml",
    "https://gist.githubusercontent.com/superseb/499f2caa2637c404af41cfb7e5f4a938/raw/930841ac00653fdff8beca61dab9a20bb8983782/k8s-dashboard-user.yml",
  ]
}

resource "local_file" "kube_cluster_yaml" {
  filename = format("%s/%s" , path.root, "kube_config_cluster.yml")
  content = rke_cluster.cluster.kube_config_yaml
}
```

`terraform apply` output
```
...
[info] [cleanup] Successfully started [rke-log-cleaner] container on host [ubuntu]
[info] [remove/rke-log-cleaner] Successfully removed container on host [ubuntu]
[info] [sync] Syncing nodes Labels and Taints
[info] [sync] Successfully synced nodes Labels and Taints
[info] [network] Setting up network plugin: canal
[info] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes
[info] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
[info] [addons] Executing deploy job rke-network-plugin

========================================


  on main.tf line 1, in resource "rke_cluster" "cluster":
   1: resource rke_cluster "cluster" {

```

**Comment by rawmind0** [comment]
@fish-finger , docker installation issue is addressed. Docker url is managed now by `var.docker_install_url` 

@ctcampbell , it seems you are getting timeout when rke is installing addons. If you tf apply again, installation should finish. Another option could be increase  `addon_job_timeout=60 | 120` argument.

**Comment by rawmind0** [comment]
Please, reopne issue if needed
