### ISSUE TITLE
restoring backup 

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#116]
Hi,

Is there some terraform configuration example to restore a new cluster from s3 backup of old cluster?

Or we just need to use the RKE command line for that?

This is an example rke command but it requires cluster.yml , but i have cluster.tf instead

```
rke etcd snapshot-restore --config cluster.yml --name snapshot-name \
--s3 --access-key S3_ACCESS_KEY --secret-key S3_SECRET_KEY \
--bucket-name s3-bucket-name --s3-endpoint s3.amazonaws.com


```
thanks

gz#10240

**Comment by linecolumn** [comment]
I'm, also, interested in this.

Having in mind 'official' restore documentation: https://rancher.com/docs/rke/latest/en/etcd-snapshots/ which are exclusively using rke command.

**Comment by vitobotta** [comment]
@iahmad-khan @linecolumn did you figure out how to do manual backups or restores? Thanks

**Comment by iahmad-khan** [comment]
@vitobotta not yet , maybe we need to generate yml file from tf , and then use the RKE command line

**Comment by vitobotta** [comment]
Hi @iahmad-khan, I found a workaround that lets me use the RKE binary to do backups and restores. I wrote about this stuff in a post - see https://vitobotta.com/2019/10/26/provisioning-rancher-ha-cluster-with-terraform/

**Comment by iahmad-khan** [comment]
Yes , as I said currently it needs to be done using rke binary and cluster
yml

**Comment by ryudice** [comment]
how do you get cluster.yml from the provider?

**Comment by iahmad-khan** [comment]
@ryudice 

I have not tried but maybe


```

resource "local_file" "rke_cluster_yaml" {
  filename = "${path.root}/rke_data/cluster.yml"
  content = rke_cluster.rancher-cluster.rke_cluster_yaml
}

```

**Comment by iahmad-khan** [comment]
Yeah , it works

**Comment by iahmad-khan** [comment]
But I see that we dont need to generate yaml and can restore the cluster from snapshot using terraform directly.

the keys are:

`restore:
    restore: false
    snapshot_name: ""`

**Comment by iahmad-khan** [comment]
Looks like the terraform restore block is not restoring anything,

```

restore {
   restore = true
   snapshot_name = "2020-01-27T13:24:09Z_etcd.zip"
  }

```

**Comment by dmildh** [comment]
Thanks for opening this @iahmad-khan I am also looking for a way to restore an HA setup using this provider.  Would be nice if we could just restore the entire cluster to a point in time, not just a single node.

**Comment by vijaytrainer** [comment]
is there any progress here, on restoring it via terraform. the restore block just doesn't work.

**Comment by iahmad-khan** [comment]
i tried this many times , and i can confirm that restore is not working from terraform although i can see the etcd rolling snapshots in /opt/rke/etcd_snapshots directory.



there is some issue with this implementation:

```

func rkeClusterRestoreFields() map[string]*schema.Schema {
	s := map[string]*schema.Schema{
		"restore": {
			Type:        schema.TypeBool,
			Optional:    true,
			Default:     false,
			Description: "Restore RKE cluster",
		},
		"snapshot_name": {
			Type:        schema.TypeString,
			Optional:    true,
			Description: "Snapshot name",
		},
	}
	return s


````

**Comment by rawmind0** [comment]
Restore feature wasn't implemented on the provider. Submitted PR #226 adding restore feature and docs

**Comment by rawmind0** [comment]
PR #226 merged into master. Please, reopen issue if needed.
