### ISSUE TITLE
some resource arguments doesn't detect config changes 

### ISSUE THREAD

**Issue by yanndegat** [rancher/terraform-provider-rke#122]
hi @yamamoto-febc 

it seems that some args ( such as services_kube_api, services_kube_cnotroller, ... )
doesn't detect changes when you change the config

To make it explicit:

you first create a cluster with
```
resource rke_cluster "myk8s" {
...
services_kube_api {
service_node_port_range = "30000-32000"
} 
...
}
```

your cluster is created

then you change only the port range
```
services_kube_api {
    service_node_port_range = "20000-32000"
}
```

terraform doesnt detect any change during the plan phase

if ever i change another arg, then the change is correctly applied

my intuition is that there may be an issue with the `isRKEConfigChanged` func here
https://github.com/yamamoto-febc/terraform-provider-rke/blob/50e8e2d5cb68ce4358c1cadfeede31c71db2cf0d/rke/resource_rke_cluster.go#L392

the d.HasChange func may not be recursive or something

maybe upgrading the terraform dependency would fix the issue ?
(still in 0.12-alpha4 in the go.mod)

**Comment by rawmind0** [comment]
This should be fixed on new provider releases. Please, reopen issue if needed.
