### ISSUE TITLE
Import the rke cluster to rancher

### ISSUE THREAD

**Issue by bkalai321** [rancher/terraform-provider-rke#131]
@Kazumichi Yamamoto,
Thanks for your great work on this. I can stand up an RKE cluster with on prem  nodes and everything is working great.the snippet is saw about terraform rancher2 import suggests that the import functionality is to import a cluster that was not created by terraform (need to test this)
what is the terraform commands to import the rke cluster to rancher?
in rancher cli I would do
rancher clusters create \
    --import  cluster-name
and  
rancher clusters import -q pilot

**Comment by rawmind0** [comment]
you can't import rke cluster to Rancher with this provider. You could doi it using [tf rancher2](https://github.com/terraform-providers/terraform-provider-rancher2) provider and the [`rancher2_cluster`](https://www.terraform.io/docs/providers/rancher2/r/cluster.html) resource

**Comment by rawmind0** [comment]
Please reopen issue if needed

**Comment by jonashartwig** [comment]
Hi, I created a cluster with rke and register it to rancher like this:

```tf
resource "local_file" "cluster_yaml" {
  filename = "${path.module}/kubeconfig/config"
  content  = module.cluster.kubeconfig
}

# register cluster to rancher
resource "null_resource" register_cluster {
  provisioner "local-exec" {
    command = "curl --insecure -sfL  ${var.cluster_registration_token.manifest_url} | kubectl --kubeconfig ${local_file.cluster_yaml.filename} apply -f -"
  }
}
```

this seems i pass terraforms way of doing it by storing a local file. You mention that this can be done using "racnher2_cluster" instead. Is there an example somewhere? I have a hard time finding any.

regards

**Comment by geanttechnology** [comment]
> Hi, I created a cluster with rke and register it to rancher like this:
> 
> ```terraform
> resource "local_file" "cluster_yaml" {
>   filename = "${path.module}/kubeconfig/config"
>   content  = module.cluster.kubeconfig
> }
> 
> # register cluster to rancher
> resource "null_resource" register_cluster {
>   provisioner "local-exec" {
>     command = "curl --insecure -sfL  ${var.cluster_registration_token.manifest_url} | kubectl --kubeconfig ${local_file.cluster_yaml.filename} apply -f -"
>   }
> }
> ```
> 
> this seems i pass terraforms way of doing it by storing a local file. You mention that this can be done using "rancher2_cluster" instead. Is there an example somewhere? I have a hard time finding any.
> 
> regards

@jonashartwig how did you construct the var.cluster_registration_token.manifest_url ?

**Comment by alik-agaev** [comment]
> Hi, I created a cluster with rke and register it to rancher like this:
> 
> ```terraform
> resource "local_file" "cluster_yaml" {
>   filename = "${path.module}/kubeconfig/config"
>   content  = module.cluster.kubeconfig
> }
> 
> # register cluster to rancher
> resource "null_resource" register_cluster {
>   provisioner "local-exec" {
>     command = "curl --insecure -sfL  ${var.cluster_registration_token.manifest_url} | kubectl --kubeconfig ${local_file.cluster_yaml.filename} apply -f -"
>   }
> }
> ```
> 
> this seems i pass terraforms way of doing it by storing a local file. You mention that this can be done using "rancher2_cluster" instead. Is there an example somewhere? I have a hard time finding any.
> 
> regards

Here is my example with creating a [new rancher cluster](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster) resource and importing terraform-rke managed one to it.
```
resource "rancher2_cluster" "cluster" {
  name        = var.cluster_name
  description = "${var.cluster_name} imported cluster"
}
```
Then pass `rancher2_cluster.cluster.cluster_registration_token[0].manifest_url` to `addons_include` parameter of the rke_cluster resource. 
```
resource "rke_cluster" "cluster" {
  ...
  addons_include = rancher2_cluster.cluster.cluster_registration_token[0].manifest_url
  ...
}
```
As you see, you don't need `local-exec` to import your cluster, because this `rancher2_cluster.cluster.cluster_registration_token[0].manifest_url` is basically an yaml manifest (by url) ready to be applied to. And `addons_include` is just a right place for manifests.

**Comment by geanttechnology** [comment]
@alik-agaev, I have tried to use the addons_include to inject the joining process as part of the rke creation and I am getting an error on my tf file "Inappropriate value for attribute "addons_include": list of string required.

**Comment by geanttechnology** [comment]
Here is what worked for me:
1) I created the cluster like so

`resource "rancher2_cluster" "cluster" {
  name = var.cluster_name
  description = "${var.cluster_name} imported cluster"
}`

2) Then injected it into the rke_cluster resource like so:

`addons_include = [
    "${rancher2_cluster.cluster.cluster_registration_token[0].manifest_url}",
  ]`
