### ISSUE TITLE
Rebuilding the worker nodes

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#133]
Currently my cluster has worker nodes running RHEL7.6.

I need to switch them all to CentOS7.6.

If I rebuild the node with Centos7 , terrafrom still see that the node is ok , but its not.
I then need to remove the node from TF , build , apply , then add it again , build and apply.

What is the recommend way. Is there some work going on detecting bad nodes and re-installing it as worker node on terrafrom apply.

thanks

**Comment by rawmind0** [comment]
Duplicate #108 

@iahmad-khan  if nothing is changing on nodes argument, the rke cluster is unable to know that an update is needed. Please, take a look to [this comment](https://github.com/rancher/terraform-provider-rke/issues/108#issuecomment-534470983)

**Comment by rawmind0** [comment]
Closing in favour of #108 . Please, reopen issue if needed
