### ISSUE TITLE
nginx ingress failing with restricted psp

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#134]
Related to : https://github.com/rancher/rancher/issues/16119

When I enable restrcited psp on all service accounts ( of my own ) , then deploying ingress through RKE is unable to deploy pods , as its trying to access host ports.

Is there a way to fix it.

I dont need ingress to access hostports  directly , I want to access the ingress controller on nodePort.

Is there some rke configuration option to run ingress on high ports like 30030 , instead of port 80 or 443.

**Comment by rawmind0** [comment]
This issue should be addressed from provider v1.0.0-rc1, due to rke was upgraded to v1.0.0.  Please test it with current provider version, and reopen issue if needed.
