### ISSUE TITLE
Apply stuck at modifying after deleting node

### ISSUE THREAD

**Issue by vitobotta** [rancher/terraform-provider-rke#136]
I have successfully tested adding a couple of nodes to a cluster with a single node initially. However when removing these two nodes, RKE is stuck at modifying the remaining node. I suspect this may be because the actual nodes/servers are deleted by the Hetzner Cloud provider before RKE updates the cluster. Could it be that it hangs because those two nodes are no longer reachable or something like that? Thanks

**Comment by rawmind0** [comment]
Could be.. Have you removed the deleted nodes from the tf file??

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
