### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by yamamoto-febc** [rancher/terraform-provider-rke#137]
Recently, I don't have enough time for maintenance this repository, so maintenance has been delayed.
Also, RKE v1.0 will be released soon and maintenance will be required for this repository.

Is there anyone interested in becoming a maintainer?

**Comment by Oats87** [comment]
@yamamoto-febc I can maintain this Terraform Provider for RKE

**Comment by rodcloutier** [comment]
@Oats87 would the provider slanted to become an official RancherLabs product?

**Comment by Oats87** [comment]
@rodcloutier there is discussion about it, but I would not be opposed to having Rancher become the official maintainer/owner of this project.

**Comment by cloudnautique** [comment]
@yamamoto-febc I'm the product manager for Rancher Labs, we would love to take this over and get it added as an official provider. 

I'll get in touch.

**Comment by ryudice** [comment]
This project has been really helpful to us, it would be great if it can be officially supported by rancher. I'm sure a few others have an investment on this as well, in our case all our non-production cluster use it.

**Comment by yamamoto-febc** [comment]
Hi all, 

Thank you for your response.
I received the email about this from @cloudnautique.

I think it is best for many users that Rancher Labs become the maintainer/owner of the RKE provider, so I decided to transfer this repo to Rancher Labs.

I believe this will make all of this provider's users happy!

**Comment by cloudnautique** [comment]
Closing this issue. 

Thank you @yamamoto-febc!
