### ISSUE TITLE
using cluster.yml

### ISSUE THREAD

**Issue by shaunc** [rancher/terraform-provider-rke#138]
When specifying cluster.yml, can we just specify parts we want to override -- e.g. `kubernetes_version`? Much of the file seems to be populated by the rke_cluster resource, and I wouldn't want to override generated keys, etc. 

Best would be to specify options directly with the rke_cluster resource rather than having to override them via cluster.yml.

**Comment by rawmind0** [comment]
This should be fixed with #185 . Please, reopen issue if needed
