### ISSUE TITLE
Deploy static pods

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#140]
Hi,

Is there a way to deploy static pods while creating a cluster? Becuase the RKE control plane is running on docker and I may lose the static pods after cluster update.

**Comment by cloudnautique** [comment]
No, there isn't a way to do that with RKE. You can deploy the manifest files in the same process as creating the VMs. When launching RKE, you can bind mount them into the kubelet containers for execution.

**Comment by cloudnautique** [comment]
I'd like to amend my earlier response. RKE services are not running via static pods.

If you would like to launch static pods, you would need to either write the manifests on the host outside of this provider, and then bind mount the directory into the kubelet directory through `extra_binds` or host manifests on a url and pass the `manifest-url` flag to kubelet.
