### ISSUE TITLE
kubeconfig being recreated every time

### ISSUE THREAD

**Issue by dmildh** [rancher/terraform-provider-rke#151]
I built the latest version of the provider and using version 0.16 for my deployment along with the local_file resource to create the kubeconfig file.  When there are no changes the terraform plan shows that the file will be recreated everytime:

Terraform will perform the following actions:

   local_file.kube_config_yaml must be replaced
-/+ resource "local_file" "kube_config_yaml" {

Along with RKE updates to support the new file:

   rke_cluster.rancher_cluster will be updated in-place
  ~ resource "rke_cluster" "rancher_cluster" {
      ~ kube_config_yaml          = (sensitive value)
     ~ rke_cluster_yaml          = (sensitive value)

Does anyone know if this is the expected behavior?  I don't remember seeing this with the 0.14 version but would need to test to validate.  Would be nice to store this in a secure s3 bucket instead of a file but will look at that after this issue.

**Comment by mitchellmaler** [comment]
Seems like a similar issue to what is being fixed in https://github.com/rancher/terraform-provider-rke/pull/150.

**Comment by jshrack-ssi** [comment]
I am seeing the same issue. With the "replacement" kubeconfig it also generates the following error with 1.0.0-rc1:

Error: Provider produced inconsistent final plan

When expanding the plan for local_file.kube_cluster_yaml to include new values
learned so far during apply, provider "registry.terraform.io/-/local" produced
an invalid new value for .content

This is even though the new kubeconfig is exactly the same as the existing.

**Comment by rawmind0** [comment]
PR #150 merged that fix this issue. Please reopen issue if needed.
