### ISSUE TITLE
Calico mtu configuration

### ISSUE THREAD

**Issue by iahmad-khan** [rancher/terraform-provider-rke#153]
Hi,

I need to be able to set MTU size in calico config section.

Is this supported now in terraform module?

https://github.com/rancher/rancher/issues/24096

**Comment by rawmind0** [comment]
Hi @iahmad-khan , not supported yet, but submitted PR #154 to do it.

**Comment by rawmind0** [comment]
PR already merged. Please reopen issue if needed
