### ISSUE TITLE
Add  audit_log and secrets_encryption_config to kube_api object.

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rke#157]
Currently you cannot add the audit_log and secrets_encryption_config settings.

**Comment by rawmind0** [comment]
You can [audit_log](https://github.com/rancher/terraform-provider-rke/blob/master/website/docs/r/cluster.html.markdown#audit_log) 
 , [secrets_encryption_config](https://github.com/rancher/terraform-provider-rke/blob/master/website/docs/r/cluster.html.markdown#secrets_encryption_config)

**Comment by mitchellmaler** [comment]
Ah I had a type and did audit_log = {} and secrets_encryption_config = {}. I just fixed it and it works. Thanks for the documentation link.
