### ISSUE TITLE
Suport policy as a filed in the audit_log Configuration

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rke#158]
Currently the audit_log configuration does not support providing the policy which means I cannot modify the created policy. You can see at https://github.com/rancher/terraform-provider-rke/blob/7d6cf50a5ded7e412d218002d35bf73a9e5c189b/rke/structure_rke_cluster_services_kube_api.go#L106 it isn't added to the AuditLogConfig object. You can find that policy is a valid field for it https://github.com/rancher/types/blob/master/client/management/v3/zz_generated_audit_log_config.go

**Comment by rawmind0** [comment]
Submitted PR #172 to support this feature

**Comment by rawmind0** [comment]
Feature already merged to master. Please, reopen issue if needed.
