### ISSUE TITLE
Anyway to get rke logs when cluster is being created or updated?

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rke#159]
I noticed the provider includes a log flag but setting that to true didn't seem to do anything unless I am misunderstanding what it is for. Basically I am interested in a way to capture the same log output the cli has and output it to stdout, file, or even exported so it can be reviewed. It does show it when a rke error occurs but would be better to show it every time and have some configuration.

**Comment by rawmind0** [comment]
Provider `debug` and `log_file` config arguments added on PR https://github.com/rancher/terraform-provider-rke/pull/173 . Included on `v1.0.0-rc3`. Please, reopen issue if needed.
