### ISSUE TITLE
[1.0 rc2] Set version from v1.16.2-rancher1-1 to v1.16.6-rancher1-2 and cluster didn't upgrade

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rke#166]
I updated my cluster resources version from v1.16.2-rancher1-1 to v1.16.6-rancher1-2 and ran terraform apply on that cluster which finished but the cluster actually didn't upgrade. Now if I run apply again it doesn't think anything needs to change. Looking at the cluster config in the state it has that version set. I was able to grab that file from the state and run rke up locally and it did upgrade the cluster.

I set the rke provider log to true and ran apply with TF_LOG=Debug but it doesn't output any RKE logs so not sure how to get those to understand what it did.
```hcl
provider "rke" {
  log = true
}
```

**Comment by mitchellmaler** [comment]
The full cluster state configmap has the kubernetesVersion set to "kubernetesVersion":"v1.16.6-rancher1-2" but running kubectl get nodes I shows "v1.16.2"

**Comment by mitchellmaler** [comment]
I redeployed the cluster resetting it to 1.16.2-rancher1-1  and then extracting the cluster.yml and state files. Then I updated the cluster.yml to the newer version and ran rke up. This time it did upgrade. So it seems using rke directly does upgrade the cluster.

**Comment by matthewmelvin** [comment]
I think I'm encountered the same issue using 1.0.0rc2 to do an upgrade.

Case 1, using provider 0.14.1 to build a cluster as v1.16.6-rancher1-2 then switching to provider to 1.0.0rc2 and upgrade cluster to  v1.15.9-rancher1-1 

Case 2, using provider 1.0.0rc2 to build a cluster as  v1.15.9-rancher1-1 then updating to v1.16.6-rancher1-2

In both cases terraform ran without error but the nodes reported as still running the old version.

**Comment by rawmind0** [comment]
There was a bug updating system_images, PR #172 fix it

**Comment by rawmind0** [comment]
Feature already merged to master. Please, reopen issue if needed.

**Comment by mitchellmaler** [comment]
@rawmind0 Can you create a new RC release so I can test this?
