### ISSUE TITLE
API server does not start because of wrong audit log policy

### ISSUE THREAD

**Issue by czunker** [rancher/terraform-provider-rke#169]
Rancher Version: 2.3.5
terraform versions:
Terraform v0.12.20
+ provider.aws v2.48.0
+ provider.rancher2 v1.7.2
k8s version: 1.17.2

I tried to setup a cluster with audit logs enabled, but the api server didn't start.
I used the example provided with [docs](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#example-usage):

    services {
      kube_api {
        audit_log {
          enabled = true
          configuration {
            max_age = 5
            max_backup = 5
            max_size = 100
            path = "-"
            format = "json"
            policy = jsonencode({"rules":[{"level": "Metadata"}]})
          }
        }
      }
    }

This results in the following error:

> I0212 12:31:11.888844    1 server.go:149] Version: v1.16.6
> 
> Error: loading audit policy file: unknown group version field audit.k8s.io/__internal, Kind=Policy in policy: from file /etc/kubernetes/audit-policy.yaml

The audit-policy.yaml looks like this:

    metadata:
      creationTimestamp: null
    rules:
    - level: Metadata

The missing pieces are:

    apiVersion: audit.k8s.io/v1
    kind: Policy

Adding this manually, the api server starts.
I also tried to add it in terraform:

    services {
          kube_api {
                audit_log {
                    enabled = true
                    configuration {
                        max_age = 5
                        max_backup = 5
                        max_size = 100
                        path = "-"
                        format = "json"
                        policy = jsonencode({"rules":[{"level": "Metadata"}], "apiVersion": "audit.k8s.io/v1", "kind": "Policy"})
                    }
                }
          }
    }

But it didn't get passed into the file. This might be because of #158.
The [rke docs](https://rancher.com/docs/rke/latest/en/config-options/audit-log/) state, it should be possible to set a policy file, but it seems the terraform provider does not know this config field:
https://github.com/rancher/terraform-provider-rke/blob/master/rke/schema_rke_cluster_services_kube_api.go#L35

Removing the line

    policy = jsonencode(....

The api server starts and the audit-policy.yaml is generated correctly:

    apiVersion: audit.k8s.io/v1
    kind: Policy
    metadata:
      creationTimestamp: null
    rules:
    - level: Metadata

**Comment by jbmcfarlin31** [comment]
@czunker It looks like the docs you are following relate to `rancher2` which is not this project. I am successfully using the audit log policy with the following configuration:
```
services {
  kube_api {
    pod_security_policy = "true"
    extra_args = {
      anonymous-auth = "false"
      admission-control-config-file = "/opt/kubernetes/admission.yaml"
      profiling = "false"
      service-account-lookup = "true"
      audit-log-maxage = "30"
      audit-log-maxbackup = "10"
      audit-log-maxsize = "100"
      audit-log-format = "json"
      audit-policy-file = "/opt/kubernetes/audit.yaml"
      audit-log-path = "/var/log/kube-audit/audit-log.json"
    }

    extra_binds = [
      "/var/log/kube-audit:/var/log/kube-audit",
      "/opt/kubernetes:/opt/kubernetes"
    ]
  }
}
```

I also pre-create the `audit.yaml ` before the cluster is spun up. So my terraform workflow basically generates it in the directories it is looking for in the cluster, using something like:
```
sudo bash -c 'cat <<EOF > /opt/kubernetes/audit.yaml
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
- level: Metadata
EOF'
```

**Comment by rawmind0** [comment]
@czunker as @jbmcfarlin31 has mentioned, the doc you reference is not this provider.

This provider will support audit log Policy definition when PR #172 is merged

**Comment by czunker** [comment]
Thank you for your clarification and please apologize any inconvenience. I'll report it for the correct provider.

**Comment by rawmind0** [comment]
Feature already merged to master. Please, reopen issue if needed.
