### ISSUE TITLE
Specify supported kubernetes_version in releases page

### ISSUE THREAD

**Issue by remche** [rancher/terraform-provider-rke#170]
You should always indicate which kubernetes version the module supports in the releases page, as RKE does (or at least on which RKE version it's based, as it's done for 1.0.0-rc2).

Thanks for the great work !

Note for users : you can see it in go.mod file (ie https://github.com/rancher/terraform-provider-rke/blob/1.0.0-rc2/go.mod)

**Comment by rawmind0** [comment]
@remche , thanks for your comment and your suggestion, we take note.

Anyway, supported rke version is specified in the [1.0.0-rc2 release CHANGELOG](https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0-rc2)
