### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by mwei0210** [rancher/terraform-provider-rke#171]
Terraform v0.12.20
rke v1.0.4
provider.rke  v1.0.0-rc2 terraform-provider-rke_linux-amd64

Got exec format error on ubuntu18.04-amd64

**Comment by rawmind0** [comment]
I've just tested binary and working fine. May be your file is corrupted, have you checked the checksum??

**Comment by rawmind0** [comment]
Please, reopen issue if needed
