### ISSUE TITLE
RKE fails to provision cluster - RKE 1.0.0-rc3

### ISSUE THREAD

**Issue by john-morsley** [rancher/terraform-provider-rke#175]
Hi guys,

I'm attempting to provision a cluster on AWS, however, it fails with the following error:

```
Failed running cluster err:[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [3.95.213.230]: Get http://localhost:10248/healthz: Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: F0301 13:32:25.053999   12053 server.go:273] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-056f93a515d729afd: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""]

```

My output: https://gist.github.com/john-morsley/dfebb9ab0d27a915e789d38c0393eac4

**Comment by rawmind0** [comment]
Hi @john-morsley , it seems that aws doesn't have credentials, have you followed iam configuration on aws, https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/??

**Comment by john-morsley** [comment]
Hi, @rawmind0, yes to the best of my knowledge and understanding.

**Comment by john-morsley** [comment]
But you have pointed me in the right direction! Thanks @rawmind0, I removed the 'cloud_provider' and it worked.

**Comment by rawmind0** [comment]
Please, reopen issue if needed
