### ISSUE TITLE
Resource 'rke_cluster.cluster' does not have attribute 'kube_config_yaml'

### ISSUE THREAD

**Issue by rushins** [rancher/terraform-provider-rke#176]
hello 

i got the following error  using terraform when executing "Resource 'rke_cluster.cluster' does not have attribute 'kube_config_yaml'" . 

here is my configuration. 
-------
resource "rke_cluster" "cluster" {
  nodes {
    address = "host1"
    user    = "root"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = "${file("~/.ssh/id_rsa")}"
  }  addons_include = [
    "https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml",
    "https://gist.githubusercontent.com/superseb/499f2caa2637c404af41cfb7e5f4a938/raw/930841ac00653fdff8beca61dab9a20bb8983782/k8s-dashboard-user.yml",
  ]
}
resource "local_file" "kube_cluster_yaml" {
  filename = "${path.root}/kube_config_cluster.yml"
  sensitive_content  = "${rke_cluster.cluster.kube_config_yaml}"
}

i have the cluster.yaml from this standard configuation provided by rancher. https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/kubernetes-rke/#

Any idea what this issue.

BR,

~

**Comment by jobygoude** [comment]
Yes, apparently the key has changed its name for `internal_kube_config_yaml`

```
resource "local_file" "kube_cluster_yaml" {
  content  = rke_cluster.cluster.internal_kube_config_yaml
  filename = local.local_kube_config_file_path

  depends_on = [rke_cluster.cluster]
}
```

**Comment by rawmind0** [comment]
No @jobygoude , in fact exist both, https://github.com/rancher/terraform-provider-rke/blob/master/rke/schema_rke_cluster.go#L364 and https://github.com/rancher/terraform-provider-rke/blob/master/rke/schema_rke_cluster.go#L370

**Comment by jobygoude** [comment]
Yes absolutely, thank you for coming back.

**Comment by rawmind0** [comment]
Please, reopen issue if needed
