### ISSUE TITLE
Downscaling fail with 1.0.0-rc3

### ISSUE THREAD

**Issue by remche** [rancher/terraform-provider-rke#178]
With the last release, downscaling a cluster throws a plan error :
`Error: Provider produced inconsistent final plan`
It was working fine before this release, could it be caused by `rke_cluster` refactorisation ?

Full output of travis job for [Terraform Openstack RKE](https://github.com/remche/terraform-openstack-rke) is here :
https://travis-ci.com/remche/terraform-openstack-rke/jobs/293619712

**Comment by rawmind0** [comment]
@remche , thanks for reporting. It's weird due to acceptance test are upscaling and downscaling cluster without any issue. Let me do some tests.

**Comment by rawmind0** [comment]
@remche , submited PR #180 to address issue. Could you please test it??

**Comment by remche** [comment]
@rawmind0, I confirm that the PR seems to fix the issue.
If you find it usefull, we could trigger a build on the openstack rke module when we have a PR on the provider.

**Comment by rawmind0** [comment]
Released 1.0.0-rc4 that include fix. Please reopen issue if needed.
