### ISSUE TITLE
RC4 - Cannot provision cluster due to rke-network-plugin-deploy-job

### ISSUE THREAD

**Issue by jbmcfarlin31** [rancher/terraform-provider-rke#183]
So I just downloaded the new provider and attempted to deploy a new cluster using it. It is a single node cluster, with nothing fancy.

It runs through the `Still creating...` process for about a minute and a half, and then errors out with the following:
```
time="2020-03-17T17:58:28Z" level=info msg="[network] Setting up network plugin: weave"
time="2020-03-17T17:58:28Z" level=info msg="[addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes"
time="2020-03-17T17:58:28Z" level=info msg="[addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes"
time="2020-03-17T17:58:28Z" level=info msg="[addons] Executing deploy job rke-network-plugin"
time="2020-03-17T17:58:28Z" level=debug msg="[k8s] waiting for job rke-network-plugin-deploy-job to complete.."

Failed running cluster err:Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

As the log states, I am using the `weave` CNI plugin which I have always used and has worked great.

I have some defaults applied to my kubernetes components to harden the security of the cluster itself - which did work in the provider that allowed kubernetes `1.15.3`.

I am trying to use kubernetes version: `v1.17.2-rancher1-2`.
I did add the `debug = true` and `log_path` but it doesn't seem to add much in terms of troubleshooting with obvious errors.

This is the contents of my `rke.tf` file:
```
# ---------------------------------------------------------------------
# RKE configuration

resource rke_cluster "cluster" {
  depends_on = [azurestack_public_ip.vmpip, azurestack_virtual_machine.vm]

  dynamic "nodes" {
    for_each = azurestack_public_ip.vmpip.*
    iterator = nodes

    content {
      address = nodes.value.ip_address
      user    = "testuser"
      role    = ["controlplane","etcd", "worker"]
      ssh_key = file("/opt/${var.deployment_name}/${var.deployment_name}")
    }
  }

  ignore_docker_version = true
  cluster_name = "${var.deployment_name}-cluster"

  # Kubernetes version
  kubernetes_version = "v1.17.2-rancher1-2"

  private_registries {
    url      = "myprivateregistry"
  }

  #########################################################
  # Network(CNI) - supported: flannel/calico/canal/weave
  #########################################################
  # There are several network plug-ins that work, but we default to canal
  network {
    plugin = "weave"
  }

  ingress {
    provider = "nginx"
    options = {
      proxy-buffer-size = "16k"
      http2 = "true"
    }
    extra_args = {
      default-ssl-certificate = "ingress-nginx/wildcard-ingress"
    }
  }

  services {
    kube_api {
      pod_security_policy = "false"
      extra_args = {
        anonymous-auth = "false"
        admission-control-config-file = "/opt/kubernetes/admission.yaml"
        profiling = "false"
        service-account-lookup = "true"
        audit-log-maxage = "30"
        audit-log-maxbackup = "10"
        audit-log-maxsize = "100"
        audit-log-format = "json"
        audit-policy-file = "/opt/kubernetes/audit.yaml"
        audit-log-path = "/var/log/kube-audit/audit-log.json"
        enable-admission-plugins = "ServiceAccount,PodPreset,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,SecurityContextDeny,PodSecurityPolicy,NodeRestriction,EventRateLimit"
        runtime-config = "batch/v2alpha1,authentication.k8s.io/v1beta1=true,settings.k8s.io/v1alpha1=true"
        tls-cipher-suites = "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      }
      # Optionally, define extra binds for the api server
      extra_binds = [
        "/var/log/kube-audit:/var/log/kube-audit",
        "/opt/kubernetes:/opt/kubernetes"
      ]
    }

    scheduler {
      extra_args = {
        address = "127.0.0.1"
      }
    }

    kube_controller {
      extra_args = {
        profiling = "false"
        address = "127.0.0.1"
        terminated-pod-gc-threshold = "1000"
        feature-gates = "RotateKubeletServerCertificate=true"
      }
    }

    kubelet  {
      extra_args = {
        volume-plugin-dir = "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
        #protect-kernel-defaults = true # requires additional config
        streaming-connection-idle-timeout = "1800s"
        authorization-mode = "Webhook"
        make-iptables-util-chains = "true"
        event-qps = "0"
        anonymous-auth = "false"
        feature-gates = "RotateKubeletServerCertificate=true"
        tls-cipher-suites = "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      }
      # Optionally define additional volume binds to a service
      extra_binds = [
        "/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec",
      ]
    }
  }
}
```

**Comment by rawmind0** [comment]
What is the result if you execute the plan again?? Is it continuing with the installation??

I think network addon is getting timeout on deployment. Setting [`addon_job_timeout`](https://github.com/rancher/terraform-provider-rke/blob/master/website/docs/r/cluster.html.markdown#argument-reference) argument should help here.

**Comment by jbmcfarlin31** [comment]
@rawmind0 If I re-run the plan again, it destroys the current cluster that failed to deploy, and attempts to redeploy again resulting in the same error.

I set the `addon_job_timeout` to `300`. The results were the same error as above.

**Comment by rawmind0** [comment]
Ok, then you should take a look to docker logs on the host, to figure out what is happening to network addon deployment.

**Comment by jbmcfarlin31** [comment]
@rawmind0 I don't see any container within docker pertaining to the network addon deployment. All `kube-{deployment,proxy,scheduler,proxy,etc.}` shows normal log output, with the exception of showing that the CNI is not initialized yet.

Since the `kube-apiserver` is up, I am able to use `kubectl` commands. I looked within the `kube-system` namespace and found the `rke-network-plugin-deploy-job` and it shows:
```
NAME                            COMPLETIONS   DURATION   AGE
rke-network-plugin-deploy-job   0/1                      12m
```

Upon doing a `describe` on that job, the following shows:
```
 Events:
  Type     Reason        Age                      From            Message
  ----     ------        ----                     ----            -------
  Warning  FailedCreate  <invalid> (x7 over 10m)  job-controller  Error creating: pods "rke-network-plugin-deploy-job-" is forbidden: no providers available to validate pod request
```

So it seems as if the pod isn't even able to initialize.

**Comment by rawmind0** [comment]
Yeah, that's what i mean. For any reason network addon is failing to start. Take a look to the logs, due to  seems that issue is more on rke side.

**Comment by jbmcfarlin31** [comment]
@rawmind0 so my cluster got past the pod creation stage earlier, turns out that if you enable the pod security policy admission controller WITHOUT defining policies beforehand, no pods will be able to deploy. It is stated [here on the kubernetes docs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#enabling-pod-security-policies).

Now, that being said, I removed the PSP section of my `rke.tf` file and attempted a redeploy however now it appears the cluster will not build and it gets stuck on trying to pull the hyperkube image:
```
time="2020-03-18T15:04:10Z" level=info msg="Pre-pulling kubernetes images"
time="2020-03-18T15:04:10Z" level=debug msg="Checking if image [rancher/hyperkube:v1.17.2-rancher1] exists on host [X.X.X.X], try #1"
time="2020-03-18T15:04:10Z" level=debug msg="Image [rancher/hyperkube:v1.17.2-rancher1] does not exist on host [X.X.X.X]: Error: No such image: rancher/hyperkube:v1.17.2-rancher1"
time="2020-03-18T15:04:10Z" level=info msg="Pulling image [rancher/hyperkube:v1.17.2-rancher1] on host [X.X.X.X], try #1"
```
If I go to the host itself, the only container that executed is the `cluster-state-deployer`. If I try to manually pull the `rancher/hyperkube:v1.17.2-rancher1` image I get that the latest image is already up to date.

Cluster creation just hangs and never fails or timeout (I left it going for 1.5hrs yesterday).

Any ideas?

**Comment by mitchellmaler** [comment]
@jbmcfarlin31 That issue sounds similar to #177

**Comment by jbmcfarlin31** [comment]
@mitchellmaler agreed it does.

**Comment by jbmcfarlin31** [comment]
Also, for whatever reason, when I re-downloaded the [amd64 rc4 version](https://github.com/rancher/terraform-provider-rke/releases/download/1.0.0-rc4/terraform-provider-rke-linux-amd64.tar.gz) today for another repo of mine, doing a `terraform plan` registered the provider as `version <= 0.7`... this worked fine yesterday when I downloaded the provider. So not sure what happened there.

I ended up taking the provider I downloaded yesterday in another repo and copying into this new repo that I am working in.

**Comment by jbmcfarlin31** [comment]
I just removed all of the security configurations for my `rke.tf` file, and only included the bare minimum just to verify. I am still getting stuck on RKE trying to pull the image... suffice to say, this is an issue and likely related to what @mitchellmaler stated in his issue.

**Comment by rawmind0** [comment]
Yeah, both issues seems so similar. It seems that eventually rke got stuck at some point pulling images and it's not returning anything. tf provider is using rke v1.0.4, trying to find any related issue on rke.

**Comment by rawmind0** [comment]
I'm not able to reproduce the issue. Just deploying rke fine on distinct nodes. 

@jbmcfarlin31 , you got same error always?? could you please try same rke installation using rke v1.0.4 binary to check if you got same error??

**Comment by jbmcfarlin31** [comment]
@rawmind0 I get the same error using the provider no matter what - always get stuck on pulling an image, in my case, it is the hyperkube image. I am trying the rke binary (v1.0.4) now. I will report what happens.

**Comment by jbmcfarlin31** [comment]
@rawmind0 So I manually deployed the cluster using RKE v1.0.4 and it looks like it was successful. It did stall a few areas trying to pull image, but it was relatively quick to get past whereas in the provider it seems to hang indefinitely.

**Comment by jbmcfarlin31** [comment]
@rawmind0 I don't know what changed from yesterday until now, but I just tried and did a redeploy and successfully got a cluster built using the provider.

**Comment by jbmcfarlin31** [comment]
@rawmind0 I just tried another deploy on a completely brand new cluster and it is showing the same hanging result of `Still creating...`.

Log output before it gets to this point is the same:
```
time="2020-03-19T16:29:00Z" level=debug msg="[version] Getting Kubernetes server version.."
time="2020-03-19T16:29:00Z" level=info msg="[certificates] Successfully deployed kubernetes certificates to Cluster nodes"
time="2020-03-19T16:29:00Z" level=debug msg="[reconcile] currentCluster: <nil>\n"
time="2020-03-19T16:29:00Z" level=info msg="[reconcile] Reconciling cluster state"
time="2020-03-19T16:29:00Z" level=info msg="[reconcile] This is newly generated cluster"
time="2020-03-19T16:29:00Z" level=debug msg="Encryption is disabled in both current and new spec; no action is required"
time="2020-03-19T16:29:00Z" level=info msg="Pre-pulling kubernetes images"
time="2020-03-19T16:29:00Z" level=debug msg="Checking if image [rancher/hyperkube:v1.17.2-rancher1] exists on host [X.X.X.X], try #1"
time="2020-03-19T16:29:00Z" level=debug msg="Image [rancher/hyperkube:v1.17.2-rancher1] does not exist on host [X.X.X.X]: Error: No such image: rancher/hyperkube:v1.17.2-rancher1"
time="2020-03-19T16:29:00Z" level=info msg="Pulling image [rancher/hyperkube:v1.17.2-rancher1] on host [X.X.X.X], try #1"
```

**Comment by rawmind0** [comment]
@jbmcfarlin31 , thanks for the update. It's annoying that issue can't be consistently reproduced. I made around 20 test installation and no issue at anyone...Still testing...

**Comment by rawmind0** [comment]
@jbmcfarlin31 , i guess that in your tests, provider is configured with `debug = true` argument, isn't it?? Could you please remove `debug` argument and test again??

**Comment by jbmcfarlin31** [comment]
@rawmind0 I changed `debug = true` to `debug = false` in the `provider` block. I then deployed a brand new cluster completely separate from other tests and had a successful deployment.
Looks like that might have been the trick.

**Comment by rawmind0** [comment]
Yeah, definitely the issue is on debug argument. Deleting debug argument or setting it to `false` address the issue. 

The problem is caused by rke docker.pullimage function when debug is set, https://github.com/rancher/rke/blob/v1.0.4/docker/docker.go#L266 . This is breaking the rke execution on non TTY and stucking the process.

**Comment by muhlba91** [comment]
i can also confirm setting `debug = false` solves this issue (and #177 too).

@rawmind0 it would be great to prevent setting this argument to the rke command or document this flag and an example use-case when it's actually working?

**Comment by rawmind0** [comment]
@muhlba91, both stuffs are done, debug argument is documented and it's not set on current version. It should work again on rke v1.1.x

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
