### ISSUE TITLE
Provider documentation is broken

### ISSUE THREAD

**Issue by AMoghrabi** [rancher/terraform-provider-rke#190]
Hello,

I'm trying to search for the provider documentation but cannot seem to find it. The link in the readme (https://www.terraform.io/docs/providers/rke/index.html) does not work either. I would appreciate your help, thanks.

**Comment by rawmind0** [comment]
Hi @AMoghrabi , we are on the process to promote the provider to be officially supported by hashicorp. Until it's not finished the onboarding process, the documentation is not available at terraform web site. 

By the moment, you can find the [provider docs](https://github.com/rancher/terraform-provider-rke/blob/master/website/docs/r/cluster.html.markdown) on this repo,

**Comment by vijaytrainer** [comment]
@rawmind0 do you have any timeline by when this provider will be moved to hashicorp.

**Comment by rawmind0** [comment]
Nope, the process was already started and now it's on hashicorp side. I guess it would depends on their workload.

**Comment by AMoghrabi** [comment]
Perfect thanks @rawmind0 . One other question unrelated to the above -- I've been trying to figure out whether RKE supports building a cluster with Windows worker nodes. Some old discussions suggest only the rancher platform can do it. Other document suggests that rancher does it through RKE. 

I don't see Windows nodes mentioned in the docs here so I assume you can't, at least not through the terraform provider. Is that correct? 

Thanks for your help!

**Comment by rawmind0** [comment]
Not an expert on windows, but if it's supported by RKE 1.1.0, it's supported by provider.

But for windows, just worker nodes are supported, https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/

**Comment by AMoghrabi** [comment]
Got it, thanks @rawmind0 . I was a little confused because the RKE documentation doesn't really specify what needs to be included in the cluster.yml to spin up windows worker nodes. I can go ask in that channel.

If you don't have anymore input on the above then I'm happy to close this ticket. Once again thanks for the help.

**Comment by AMoghrabi** [comment]
I actually spoke with someone from Rancher and I was able to confirm the RKE CLI cannot provision Windows worker nodes yet. 

Thanks for the help!

**Comment by rawmind0** [comment]
> I actually spoke with someone from Rancher and I was able to confirm the RKE CLI cannot provision Windows worker nodes yet.

Yes, this is confirmed.

Please, reopen issue if needed.
