### ISSUE TITLE
RKE installing new cluster fails in first attempts

### ISSUE THREAD

**Issue by jonashartwig** [rancher/terraform-provider-rke#193]
Hi,

I use rke-provider.rc04. When I create a new cluster with RKE in the first run I always get this error:
```
time="2020-04-15T11:55:53+02:00" level=warning msg="[etcd] host [ra003-k8s-cdl-d.ddc.teliasonera.net] failed to check etcd health: failed to get /health for host [ra003-k8s-cdl-d.ddc.teliasonera.net]: Get https://ra003-k8s-cdl-d.ddc.teliasonera.net:2379/health: remote error: tls: bad certificate"

Failed running cluster err:[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [ra001-k8s-cdl-d.ddc.teliasonera.net,ra002-k8s-cdl-d.ddc.teliasonera.net,ra003-k8s-cdl-d.ddc.teliasonera.net] failed to report healthy. Check etcd container logs on each host for more information
```

If I restart terraform apply ETCD is up and running. Maybe something that can be fixed with longer timeouts?

Regards

**Comment by rawmind0** [comment]
Hi @jonashartwig , by the error you are attaching, it seems that the node is being reused from other rke installation without cleaning it up first. May be??

If it may be the case, could you please clean up the node before doing another rke installation?? https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/#docker-containers-images-and-volumes

**Comment by jonashartwig** [comment]
thank you, that solved the problem! i am sorry i missed that.
