### ISSUE TITLE
Kubeconfig error deploying Rancher cluster

### ISSUE THREAD

**Issue by sosoriov** [rancher/terraform-provider-rke#200]
RKE Provider  version: v1.0.0-rc5

```sh
Error: Provider produced inconsistent final plan

When expanding the plan for local_file.kube-cluster-yaml to include new values
learned so far during apply, provider "registry.terraform.io/-/local" produced
an invalid new value for .content: was cty.StringVal("apiVersion: v1\nkind:
Config\nclusters:\n- cluster:\n    api-version: v1\n
certificate-authority-data:
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0R...
```

I got this error  while running the rancher helm release:

```
resource "helm_release" "rancher" {
  name  = "rancher"
  namespace = "cattle-system"
  repository = data.helm_repository.rancher-latest.metadata[0].name
  chart = "rancher-latest/rancher"
  version = "v2.3.5"
  timeout = 600
  wait = true

  set {
    name = "ingress.tls.source"
    value = "letsEncrypt"
  }

  set {
    name = "letsEncrypt.email"
    value = var.lets-encrypt-email
  }

  set {
    name = "letsEncrypt.environment"
    value = var.lets-encrypt-environment
  }

  set {
    name = "hostname"
    value = var.rancher-hostname
  }

  set {
    name = "addLocal"
    value = "true"
  }
}
```

**Comment by rawmind0** [comment]
Could you please add your full tf file, in order to clarify your issue??

**Comment by sosoriov** [comment]
This is the link to my repo.

https://github.com/sosoriov/cattle-drive/blob/master/terraform-module/rancher-setup-module/main.tf#L43

Thanks!

**Comment by rawmind0** [comment]
It seems that the local_file provider is producing inconsistent plan. Could you provide full error message?? 

BTW, you don't need to use local_file for that, you can configure helm provider in a cleaner way, https://github.com/rawmind0/tf-module-rancher-server/blob/master/provider.tf#L14, that could be output from rke provider, https://github.com/rawmind0/tf-module-rke-cluster/blob/master/output.tf

**Comment by sosoriov** [comment]
@rawmind0 thanks for your answer. Let me try to get rid of the local file first. Thanks for the example it looks cleaner indeed!

I'll come back to you.

**Comment by sosoriov** [comment]
Hi @rawmind0  I was able to get rid off the local provider and i don't have the issue anymore. I still have issues with certificates, but that's something else, no RKE related.

Thanks for your help
