### ISSUE TITLE
Error: Failed to instantiate provider "rke" to obtain schema: fork/exec permission denied

### ISSUE THREAD

**Issue by andrewlynch** [rancher/terraform-provider-rke#204]
I've been attempting to install without any success. 

After reading #189, I renamed `terraform-provider-rke` and deleted .terraform from my project directory and was able to successfully run `terraform plan`

However, when following the next step in the tutorial and running `terraform apply --auto-approve`
I receive the following error: 
`Error: Failed to instantiate provider "rke" to obtain schema: fork/exec /home/ec2-user/.terraform.d/plugins/linux_amd64/terraform-provider-rke_v0.14.1: permission denied`

**Comment by jonashartwig** [comment]
Hi, try a `chmod +x /home/ec2-user/.terraform.d/plugins/linux_amd64/terraform-provider-rke_v0.14.1` I have to do that on my mac.

**Comment by rawmind0** [comment]
@andrewlynch , as @jonashartwig it seems that the downloaded `/home/ec2-user/.terraform.d/plugins/linux_amd64/terraform-provider-rke_v0.14.1` doesn't have execution permission, adding it should address the issue. Also, a more recent version of the provider binary is recommended, [v1.0.0](https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0)

Please, reopen issue if needed.
