### ISSUE TITLE
Error: Failed to instantiate provider "rke" to obtain schema: exec format error

### ISSUE THREAD

**Issue by dilipk8** [rancher/terraform-provider-rke#205]
Hi,
I am trying out the instructions from - https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/
I get this error - while running terraform plan-

`Error: Failed to instantiate provider "rke" to obtain schema: fork/exec /home/ubuntu/.terraform.d/plugins/terraform-provider-rke_v0.14.1: exec format error`

Terraform v0.12.25
+ provider.aws v2.41.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.rancher2 v1.8.3
+ provider.rke v0.14.1

How do i resolve this.

**Comment by remche** [comment]
Seems like the plugin you downloaded does not match you CPU architecture...

**Comment by rawmind0** [comment]
@dilipk8 , as @remche mentioned be sure you download the proper platform binary. Also, a more recent version of the provider binary is recommended, [v1.0.0](https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0)

Please, reopen issue if needed.

**Comment by dilipk8** [comment]
Thanks @rawmind0
