### ISSUE TITLE
No error if fail to create nodes

### ISSUE THREAD

**Issue by pravindra01** [rancher/terraform-provider-rke#206]
rke provider creates cluster and everything looks great.
ut sometimes it fails to create some nodes, and don't give error while performing terraform apply.

I creating 3 etcd,control plane node.
and 3 worker nodes.

but after performing terraform apply, there was only 2 worker nodes.

terraform rke provider version: 1.0.0

**Comment by rawmind0** [comment]
How are you creating nodes?? What is the rke log on terraform apply??

**Comment by pravindra01** [comment]
Closing this issue, as i did ran test a couple of times and didn’t encounter the issue again
