### ISSUE TITLE
Remove commit number in release tar

### ISSUE THREAD

**Issue by pgaxatte** [rancher/terraform-provider-rke#209]
The current release (v1.0.0) tarball (and older too as far as I can tell) contains the provider binary in a directory named `terraform-provider-rke-9c95410`.
This makes it hard to predict and script for automatic installation in a container for instance.

Steps to reproduce:
```
$ wget https://github.com/rancher/terraform-provider-rke/releases/download/1.0.0/terraform-provider-rke-linux-amd64.tar.gz

$ tar tzf terraform-provider-rke-linux-amd64.tar.gz
./
./terraform-provider-rke-9c95410/
./terraform-provider-rke-9c95410/terraform-provider-rke
```

Could you make a flat tarball or have a predictable directory inside?
It seems like it should be the case when I look at https://github.com/rancher/terraform-provider-rke/blob/master/scripts/version.sh#L10 and https://github.com/rancher/terraform-provider-rke/blob/master/scripts/gopackage.sh#L19

**Comment by rawmind0** [comment]
Updated on PR https://github.com/rancher/terraform-provider-rke/pull/213

**Comment by pgaxatte** [comment]
Thanks, I'll confirm and close when the next release is out

**Comment by rawmind0** [comment]
Take a look, https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.1

**Comment by pgaxatte** [comment]
Thank you that's what I was hoping for!
