### ISSUE TITLE
How can we name/rename existing nodes ?

### ISSUE THREAD

**Issue by yanndegat** [rancher/terraform-provider-rke#210]
hi

i have a list of nodes described as follows:

```
  nodes = concat(
 [
for m in local.infra.hosts["masters"] : { 
address   = m.public_ipv4
ip        = m.public_ipv4
node_name = m.name
role      = ["controlplane", "etcd"] 
user      = m.ssh_user    
labels = {        
monitored = "enabled"   
}
taints = []
}
], [
for m in local.infra.hosts["workers"] : {
address   = m.public_ipv4 
ip        = m.public_ipv4 
node_name = m.name  
role      = ["worker"]
user      = m.ssh_user
labels = {
"monitored"               = "enabled"
}
taints = []
}
]
```

Result:

node names when using `kubectl get nodes` are set to the cluster_node/address

Expected behaviour ?
node names when using `kubectl get nodes` should be set to the cluster_node/node_name

Debug info:

```
terraform providers
.
├── provider.rke ~> 1.0.0
├── provider.terraform
```

terraform output cluster_yaml
```
- nodeName: xxx-masters-000 
address: 1.2.3.4 
port: "22"
internal_address: ""
role:   
- controlplane
- etcd
hostname_override: "" 
user: ubuntu
docker_socket: "" 
ssh_key: "" 
ssh_key_path: "" 
ssh_cert: ""  
ssh_cert_path: "" 
labels:    
monitored: enabled  
taints: []  
```

**Comment by rawmind0** [comment]
Hi @yanndegat , by default RKE is setting node `address` as k8s node name. Have you tried using  `hostname_override = xxx-masters-000`?? Is hostname `xxx-masters-000` resolvable by dns??

**Comment by yanndegat** [comment]
hi @rawmind0 

thank you very much for your quick answer.

i've tried yesterday after some digging hostname_override and it works. i was thinking that "node_name" would apply to the metadata/name of the nodes

> Is hostname xxx-masters-000 resolvable by dns??
no it''s not. it has to be ?

**Comment by rawmind0** [comment]
Cool, i'm glad your issue is solved. 

About my previous question, `is `xxx-masters-000`  resolvable by dns??`, forget it my fault here. It's not required, https://rancher.com/docs/rke/latest/en/config-options/nodes/#overriding-the-hostname
