### ISSUE TITLE
Update for RKE v1.1.2

### ISSUE THREAD

**Issue by mcmcghee** [rancher/terraform-provider-rke#212]
Is it possible to update the Terraform provider for RKE 1.1.2? Released 17 days ago and it addresses multiple CVEs, updates nginx, and allows Kubernetes v1.17.6-rancher2-1.

It would be great if the terraform provider and RKE releases were in sync. 

Learning Go is on my to-do list. But if instructions are provided on how to update the provider with new RKE releases, I will gladly help where I can and submit these pull requests.

**Comment by rawmind0** [comment]
RKE v1.1.3 is going to be released very soon.. provider is prepared to be released with it.

**Comment by rawmind0** [comment]
PR #213 is updating provider to use RKE v1.1.3

**Comment by rawmind0** [comment]
Release v1.0.1 supporting rke v1.1.3. Please, reopen issue if needed.
