### ISSUE TITLE
Releases should follow naming scheme

### ISSUE THREAD

**Issue by remche** [rancher/terraform-provider-rke#214]
Provider files should be distributed with an appropriate filename (ie. terraform-provider-rke_v1.0.0) :
https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions

Currently, if we don't change the filename, provider is marked as unversioned, and we cant constrain it.

**Comment by rawmind0** [comment]
Take a look to PR https://github.com/rancher/terraform-provider-rke/pull/213

**Comment by rawmind0** [comment]
Duplicated #209
