### ISSUE TITLE
Inconsistent release URLs

### ISSUE THREAD

**Issue by anutting** [rancher/terraform-provider-rke#221]
Hey all,

I'm writing a script to download and unpack the plugin, but the download URLs seem to be inconsistent.

The readme says to use `https://github.com/rancher/terraform-provider-rke/releases/download/x.x.x/terraform-provider-rke_<platform>` however that returns a 404 when downloading the latest 1.0.1 release `https://github.com/rancher/terraform-provider-rke/releases/download/1.0.1/terraform-provider-rke_darwin_amd64.tar.gz`

it seems the platform format has changed with this new release: "darwin_amd64" vs "darwin-amd64"
Also it seems the version format has changed as well "v1.0.1" versus "1.0.0"

I've tried several variations of the URL with just "not found" as a result. I'd like to have this script ran reliably in a CI environment so consistency moving forward would really be nice.

thanks!

**Comment by rawmind0** [comment]
Hey @anutting, we are adapting provider to be published on [terraform registry](https://registry.terraform.io/), that's the reason of the release naming changes. README.md is not updated yet.

Your link should be, `https://github.com/rancher/terraform-provider-rke/releases/download/v1.0.1/terraform-provider-rke_1.0.1_darwin_amd64.zip`

Release naming changes:
* Git tag: Semantic Version preceded with a v. Like, `v1.0.1`
* Archives: (all in zip format) terraform-provider-rke_1.0.1_{OS}_{ARCH}.zip
  * Binary: terraform-provider-rke_v1.0.1
* Checksum: terraform-provider-rke_1.0.1_SHA256SUMS
* GPG checksum sign: terraform-provider-rke_{VERSION}_SHA256SUMS.sig

Take a look to [hashicorp release naming](https://www.terraform.io/docs/registry/providers/publishing.html#manually-preparing-a-release)

**Comment by anutting** [comment]
great, thanks for the info. Nice to hear you're making steps to move to terraform registry! I didn't even know about this provider until a Rancher contact told me.
