### ISSUE TITLE
Failed initialization of cluster attempting to resize cluster size

### ISSUE THREAD

**Issue by gyalowitzdtlr** [rancher/terraform-provider-rke#225]
When trying to resize cluster with additional controllers/workers, the run fails with this error:

**Errors**
![cluster_resize_failure](https://user-images.githubusercontent.com/59739698/86553231-20e1a300-bf18-11ea-92a6-beec2fc59e87.png)

**Versions**
![terraform_versions](https://user-images.githubusercontent.com/59739698/86553332-774ee180-bf18-11ea-8307-f14abe87aca7.png)

**Comment by rawmind0** [comment]
It seems you have a duplicated node on your config.

**Comment by rawmind0** [comment]
PR #239 should address this issue and is merged. Please, reopen issue if needed.
