### ISSUE TITLE
It is not clear how to correctly add and remove nodes from rke cluster

### ISSUE THREAD

**Issue by luminiscence** [rancher/terraform-provider-rke#229]
Maybe I got something wrong, but it seems that node declarations are processed by index, so if I remove node from the middle, remaining nodes are shifted up, so 3rd node becomes 2nd, 2nd becomes 1st - and the same for new nodes. 
For example, if I have a cluster, provisioned with declaration

	resource "rke_cluster" "k8s_cluster" {
	  nodes {
		address = "192.168.50.10"
		user = "vagrant"
		role = ["controlplane", "etcd"]
	  }
	  
	  nodes {
		address = "192.168.50.11"
		user = "vagrant"
		role = ["worker"]
	  }

	  nodes {
		address = "192.168.50.12"
		user = "vagrant"
		role = ["worker"]
	  }
	}

and I remove 11th node commenting its lines, terraform plan gives me the following:

        nodes {
            address           = "192.168.50.10"
            hostname_override = "192.168.50.10"
            internal_address  = "192.168.50.10"
            role              = [
                "controlplane",
                "etcd",
            ]
        }
      ~ nodes {
          ~ address           = "192.168.50.11" -> "192.168.50.12"
            hostname_override = "192.168.50.11"
            internal_address  = "192.168.50.11"
            role              = [
                "worker",
            ]
        }
      - nodes {
          - address           = "192.168.50.12" -> null
          - hostname_override = "192.168.50.12" -> null
          - internal_address  = "192.168.50.12" -> null
          - role              = [
              - "worker",
            ] -> null
        }

so, according to the plan, 12th node will be removed and 11th node renamed to 12th. Applying it will cause 11th node to become NotReady because of misconfiguration (address not equals to k8s node name) and 12th (!) node to delete. 
Can you explain the process of adding/removing nodes? Without detailed instruction anyone can ruine their cluster in a most inobvious way. Thanks!

gz#11746

**Comment by rawmind0** [comment]
You are right @luminiscence . `nodes` argument is a terraform list and unfortunately is dependent of the postiion. PR #239  is adding a fix to properly shift the `nodes` list if required.

**Comment by rawmind0** [comment]
PR #239 is already merged. Please, reopen issue if needed.
