### ISSUE TITLE
It is not clear how to enable monitoring in "local" (upstream) cluster using RKE 1.0.1

### ISSUE THREAD

**Issue by raul-gherman-idnow** [rancher/terraform-provider-rke#231]
It is not clear how to enable monitoring in "local" (upstream) cluster using RKE 1.0.1 for resource "rke_cluster"

please provide a little guidance / documentation

**Comment by rawmind0** [comment]
RKE can't enable monitoring on k8s clusters, just deploy [metrics server](https://rancher.com/docs/rke/latest/en/config-options/add-ons/metrics-server/). 

Due to your reference to `local` cluster, i'm guessing you are referencing Rancher2 provider, not this one. Could you please clarify??

**Comment by rawmind0** [comment]
@raul-gherman-idnow , please open the issue on [Rancher2 provider](https://github.com/rancher/terraform-provider-rancher2) if it's the case, or reopen this issue if needed.
