### ISSUE TITLE
[FEATURE-REQUEST] Add rke state to the rke_cluster for additionnal operation with the CLI

### ISSUE THREAD

**Issue by julienym** [rancher/terraform-provider-rke#238]
If I am not wrong, to use the rancher cli with a cluster RKE created with this provider, we are missing the RKE state.

The idea is to offer some kind of access to this state for CLI operation that are not yet provided with this provider.

**Comment by rawmind0** [comment]
Have you tried using [`rke_state`](https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#rke_state) attribute??

**Comment by julienym** [comment]
I tested and outputed the whole rke_cluster and didn't see it. Will try again, thanks

**Comment by julienym** [comment]
Worked! Thanks
