### ISSUE TITLE
RKE provider vs rancher2 provider On prem

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rke#240]
Hi 

What I'm trying to do is create a K8s cluster via rancher2 terraform provider and register existing bare metal on-prem host nodes to it. 
I'm able to use the terraform provider to create a cluster but I have a hard time adding new nodes. 

The Rancher2 Terraform provider rke_config section doesn't have a section for adding the node, like in the terraform-provider-rke. 
I started using these provisoners to register the nodes, but I have a feeling i'm doing it the wrong way.

```
resource "null_resource" "cluster" {
 
  depends_on = [rancher2_cluster.cluster-rke]
  connection {
       private_key = file("/u/user/.ssh/id_rsa")
       type        = "ssh"
       user        = "admin"
       host        = "192.168.1.10"
  }

  provisioner "file" {
    source      = "${path.module}/scripts/"
    destination = "/tmp/"

    on_failure = fail
  }

  provisioner "remote-exec" {
    inline = [
       "sudo ls -l /tmp/",
       "sudo chmod +x /tmp/*sh",
       "sudo /tmp/setup_node.sh"
    ]
  } 
```

Thanks for any guidance.

**Comment by rawmind0** [comment]
Hi @mikekuzak,

rancher2 nor rke providers are taking care to deploy infrastructure:
* On rancher2 provider, you have the option to use node_pool and node_template to let Rancher2 deploy vm's on the configured iaas provider, but i'm guessing this doesn't fit in your architecture. If you are deploying a custom rke cluster (without iaas provider integration), you should deploy nodes and execute `node_command` to onboard them into the k8s cluster. Using tf provisioner could be a solution, but i'd recommend you to better use cloud_init on vm's including `node_command` execution. As example, take a look to https://github.com/rawmind0/tf-module-rancher-infra-aws
* On rke provider, you can add nodes (already deployed) to the config and rke will ssh to them to install required k8s software. In the case you wanted this cluster managed by Rancher2, you could import it, executing `command` or `insecure_command` on the k8s cluster.

**Comment by mikekuzak** [comment]
Hi @rawmind0 

Thanks for the reply and for some clarification. 

"Using tf provisioner could be a solution, but i'd recommend you to better use cloud_init on vm's including"
In my case we have 3 bare metal servers with the OS already installed to be used as worker nodes. No VMs. 

The rke provider seems to be able to add already deployed hosts, am I correct to assume the Rancher2 profiver does not have this feature (only support for dynamic iaas providers +vsphere) ?

Right, so the second approach would be to create the cluster and register the nodes via the rke provider and then use the Rancher2 provider to create a rancher install and import that cluster created by the rke provider ? I was under the assumption you lose some rancher features when you import a cluster vs creating the cluster from Rancher.

**Comment by rawmind0** [comment]
> "Using tf provisioner could be a solution, but i'd recommend you to better use cloud_init on vm's including"
In my case we have 3 bare metal servers with the OS already installed to be used as worker nodes. No VMs.

If you are using bare metal nodes, it'd depend how you are installing them. If the installation is automated, may be you can also add cloud_init on install. If manually, you'd need ssh them and run node_command if rancher2 is used.

> The rke provider seems to be able to add already deployed hosts, am I correct to assume the Rancher2 profiver does not have this feature (only support for dynamic iaas providers +vsphere) ?

As mentioned, if you are not using iaas provider integration (node_pool, node_template), rancher2 is not connecting to nodes to execute the node_command, it has to be done externally (automated or manually). On the other hand, rke is actively connecting to nodes to install k8s software. 

> Right, so the second approach would be to create the cluster and register the nodes via the rke provider and then use the Rancher2 provider to create a rancher install and import that cluster created by the rke provider ? I was under the assumption you lose some rancher features when you import a cluster vs creating the cluster from Rancher.

Imported and custom cluster has distinct features on rancher2 https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/ . Basically, you should decide who is managing the k8s clusters lifecycle/operation:
* rke for imported clusters.
* rancher2 for custom clusters.

**Comment by mikekuzak** [comment]
Last question :) when I use  node_command and remote tf provisioner this will register the host into the K8s cluster. What happens when I run terraform destroy, does the rancher2 provisioner cleanup after itself on the registered hosts ? 

"When the node is in Active state, removing the node from a cluster will trigger a process to clean up the node. Please restart the node after the automatic cleanup process is done to make sure any non-persistent data is properly removed."

How do I trigger the above, or does the cluster destroy from the Rancher2 provisoner do that ? 
If not, would I  need to run the manual script on the nodes?

```
provisioner "remote-exec" {
    depends_on = [rancher2_cluster.cluster-rke]
    when    = destroy

    inline = [
       "curl https://github.com/rancher/rancher/blob/master/cleanup/user-cluster.sh | sudo bash"
    ]
```


https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/#

**Comment by rawmind0** [comment]
Nodes are cleaned up on clusters managed by Rancher. RKE is not cleaning up nodes, just removing them from the rke cluster. You should clean up the nodes, manually or automated.

Anyway, try and test both and see what is a better fit for your installation.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
