### ISSUE TITLE
Plugin Directory correction

### ISSUE THREAD

**Issue by chadsly** [rancher/terraform-provider-rke#247]
The plugin directory in the README says that the syntax for a custom plugin path is "-plug-in=/my/custom/path".  I believe the terraform syntax is incorrect.  According to https://www.terraform.io/docs/commands/init.html#plugin-dir-path the syntax should be "-plugin-dir=/my/custom/path"

**Comment by rawmind0** [comment]
@chadsly  thanks for reporting. PR #254 is fixing the typo.
