### ISSUE TITLE
Azure examples needed

### ISSUE THREAD

**Issue by Tejeev** [rancher/terraform-provider-rke#252]
It would be very helpful to have Azure examples here: 
terraform-provider-rke/examples/

**Comment by rawmind0** [comment]
Azure examples can be found at [rancher/quickstart](https://github.com/rancher/quickstart/tree/master/azure)

**Comment by Tejeev** [comment]
Right, but this is to say it would be helpful to have them in terraform-provider-rke/examples/ as customers go there when creating their terraform scripts
