### ISSUE TITLE
Keep latest terraform RKE version in line with upstream RKE

### ISSUE THREAD

**Issue by zaggash** [rancher/terraform-provider-rke#260]
As of today, the RKE GO module used (v1.2.0 )  is behind the RKE release (v1.2.1).
So the Kubernetes versions available are a bit behind, which could be a problem if a severe CVE comes up.

How would you deal with the system images/kubernetes version available in case of a severe CVE ?

gz#13168

**Comment by rawmind0** [comment]
PR is already created to update RKE to v1.2.1 https://github.com/rancher/terraform-provider-rke/pull/258

**Comment by zaggash** [comment]
Is there something planned in case of CVE to get the new Kubernetes images available as soon as possible?

**Comment by rawmind0** [comment]
It already was on the way, released new [v1.1.4](https://registry.terraform.io/providers/rancher/rke/latest)  supporting rke v1.2.1
