### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rke#262]
Yesterday, I updated my rke to v1.1.4 and applied the configuration without any change. During terraform apply I started getting `Error: Provider produced inconsistent final plan` for `rke_cluster.cluster.client_cert`. The issue was resolved only after I reverted to `v1.1.3`.

Terraform version: v0.13.5

**Comment by abhi1693** [comment]
@rawmind0 Any update on this?

**Comment by rawmind0** [comment]
The only diff on provider [from v1.1.3 to v1.1.4]( https://github.com/rancher/terraform-provider-rke/compare/v1.1.3...v1.1.4) is the supported RKE version,

**Comment by abhi1693** [comment]
@rawmind0 You are correct. I think the issue was probably with terraform. I again ran my simulation and it passed without any issues.

Thank you for your support. I'll close this issue now.
