### ISSUE TITLE
Docker logging driver configuration

### ISSUE THREAD

**Issue by kostas-rs** [rancher/terraform-provider-rke#267]
I have a relatively new install of k8s version `v1.17.13-rancher1-2` using the latest version of the RKE Terraform provider and i noticed that the when running `docker inspect` for any of the running containers there is no config passed to it that rotates the logs.

This causes `kubelet` and other containers to fill up the disk which eventually runs out of space.

I guess i could configure the docker daemon to use a default config for log rotation, but i would like to know if there is any way to enable this through the provider.

Thank you

**Comment by xom4ek** [comment]
This provider use [rke](https://github.com/rancher/rke), some docs you can find [here](https://rancher.com/docs/rke/latest/en/).

Unfortunately this kubernetes distributive didn't include any docker configs and leaves it behind the scenes at your discretion.
