### ISSUE TITLE
The link provided is no longer valid, and prevents understanding of default system image tags for RKE

### ISSUE THREAD

**Issue by eengelking** [rancher/terraform-provider-rke#268]
The URL in the commented section, seen in the link below, no longer exists.  As a result, the information is out of date and is not helpful for research and/or understanding what default tags are in use.

https://github.com/rancher/terraform-provider-rke/blob/20c256b4d449c162013cee625f0ab5c5016f7e15/examples/full/example.tf#L114

**Comment by rawmind0** [comment]
Yeah, this url is not available since some time ago. RKE system images versions are managed now by [kontainer-driver-metadata](https://github.com/rancher/kontainer-driver-metadata/blob/release-v2.5/rke/k8s_rke_system_images.go)

**Comment by rawmind0** [comment]
Submitted PR to fix it, https://github.com/rancher/terraform-provider-rke/pull/283

**Comment by rawmind0** [comment]
PR merged and link updated. 

Please, reopen issue if needed.
