### ISSUE TITLE
rke2 support

### ISSUE THREAD

**Issue by ba-work** [rancher/terraform-provider-rke#271]
I would like to be able deploy rke2 using a terraform provider.

I have seen this but it isn't anything special: https://github.com/rancher/rke2-build

I'm not sure if it would preferable to add support here or break it out in to a different provider like rancher2

**Comment by rawmind0** [comment]
Rke2 is not gonna be supported on this tf provider. We are working on a new tf provider to support it, but yet in early stage.

**Comment by rgl** [comment]
any news about the rke2 terraform provider?

**Comment by erSitzt** [comment]
Is there a timeframe when this will be made public ?

**Comment by janlauber** [comment]
Would be awesome, if the terraform provider would available in near future.

**Comment by r65535** [comment]
@rawmind0 - Is there any progress on the RKE2 tf provider?
If it's not completed, could it be opened up to the community to help finish it off?

**Comment by rawmind0** [comment]
@r65535 , not sure, not in the org anymore.

**Comment by raelix** [comment]
any updates on this?

**Comment by aacoliveira** [comment]
Any news ?
