### ISSUE TITLE
[Feature] Mark ssh_key as sensitive value

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rke#275]
`ssh_key` should not be displayed in the output for `terraform plan` and `terraform apply`. For some organizations where the security policies are strict, this poses a security threat.

**Comment by rawmind0** [comment]
`ssh_key` is already set as sensitive value at [node.ssh_key](https://github.com/rancher/terraform-provider-rke/blob/master/rke/schema_rke_cluster_node.go#L90) and at 
[bastion_host.ssh_key](https://github.com/rancher/terraform-provider-rke/blob/master/rke/schema_rke_cluster_bastion_host.go#L45) . What `ssh_key` argument are you referencing??

**Comment by abhi1693** [comment]
This is was a terraform issue and has been resolved in I think v0.14.x.
