### ISSUE TITLE
To add ACI CNI network plugin support to terraform-provider-rke

### ISSUE THREAD

**Issue by Bhavanaashok33** [rancher/terraform-provider-rke#280]
Currently we support ACI CNI network plugin for RKE 1.2.4. 

We would also like to add ACI-CNI support for terraform-provider-rke

Reference : 
https://github.com/rancher/rke/commit/4f062997bbad6e7e6a82878116198853e81847d3#diff-d4ecbdb0cf2e7bf588e89882093414c03122e317be2367865ce29796c57cf403
https://github.com/rancher/kontainer-driver-metadata/commit/3fac440e14ce24b850ff6c418b49bee8e3f73b0e
https://github.com/rancher/kontainer-driver-metadata/commit/54ec7d8d139a24caf13df2e948cece69448d2896
https://github.com/rancher/kontainer-driver-metadata/commit/dea84206badf1a4e05e83222d56d2ac751a82b57

If it sounds good,  I can create a PR and the changes would include the template and arguments to add ACI-CNI network plugin as a network provider option in terraform-provider-rke

**Comment by rawmind0** [comment]
> If it sounds good, I can create a PR and the changes would include the template and arguments to add ACI-CNI network plugin as a network provider option in terraform-provider-rke

@Bhavanaashok33 , sounds pretty good. A PR for this topic would be appreciated, thanks.

**Comment by Bhavanaashok33** [comment]
I have pushed the changes : https://github.com/rancher/terraform-provider-rke/pull/282 
Please take a look at it

Thanks

**Comment by rawmind0** [comment]
Thanks @Bhavanaashok33 .. I'll review it tomorrow

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rke/pull/282 already merged. The feature will be available on next tf provider release, expected for first march week.

Thanks for the PR @Bhavanaashok33 , please, reopen the issue if needed.

**Comment by Bhavanaashok33** [comment]
Thank you for the quick response. 
Sure, I will create a new issue to incorporate further changes of rke upstream wrt aci cni.
