### ISSUE TITLE
Support for K3s

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rke#284]
Hi 

is there any support planned for creating a K3s cluster ?

**Comment by rawmind0** [comment]
Hi @mikekuzak , we are valuing the idea to create a new tf provider to support K3S/RKE2 but not within this RKE tf provider, due to the way to deploy a K3S/RKE2 cluster is quite different from RKE

**Comment by stefandanaita** [comment]
Hi @rawmind0, are you still planning/thinking of creating a rke2/k3s tf provider?
