### ISSUE TITLE
Terraform plan failed on existing clusters with v1.2.0

### ISSUE THREAD

**Issue by gladavius** [rancher/terraform-provider-rke#286]
Release v1.2.0 of the rke provider failed when trying to run a terraform plan on existing rke cluster

## Expected Behavior

Terraform plan should be able to update existing clusters created with previous versions of the provider

## Current Behavior

Terraform plan failed with the following error :
```
Error:
============= RKE outputs ==============
time="2021-03-03T15:29:38-05:00" level=info msg="Reading RKE cluster 715ea288-3de3-4b87-9dba-fd9910b65a75 ..."

Invalid address to set: []string{"services", "0", "etcd", "0", "backup_config", "0", "timeout"}
========================================
```

## Possible Solution
It might be related to this commit that added a new argument timeout for etcd backup : 

https://github.com/rancher/terraform-provider-rke/commit/c2f71bb4880c4da2bbef1c503ceacf0dc97b8b52

## Steps to Reproduce
1. Create a cluster with the rke provider version v1.1.7
2. Update the provider to v1.2.0
3. Run terraform plan

## Context (Environment)
All of our clusters are affected since we are always using the latest version of the provider in our deployments.

As a workaround we will hardcode the version v1.1.7

**Comment by rawmind0** [comment]
@gladavius ,thanks to report it. Fixed with PR https://github.com/rancher/terraform-provider-rke/pull/287

**Comment by rawmind0** [comment]
Releasing v1.2.1 in a few minutes.

**Comment by gladavius** [comment]
Thank you for your incredibly fast answer/fix @rawmind0
