### ISSUE TITLE
Drain on node destruction

### ISSUE THREAD

**Issue by aledegano** [rancher/terraform-provider-rke#290]
Hello!
Since RKE provides the logic to drain a node before upgrading it, I was wondering if the same could be invoked when a node is destroyed/removed from the cluster.

We have few use-cases where that feature would be very useful:

- Scaling-in a cluster
- Replacing the VM images (e.g. upgrades in an immutable infra)
- Tearing down a temporary infra (development, testing etc...)

Just to add some context: currently we drain the nodes that are going to be destroyed through a null-resource/local-exec which invokes `kubectl` on the operator workstation. While this approach works, you can easily see why is not particularly "clean" nor robust.

I'd like to get the discussion going and see if what I am thinking does even make sense. If it does I might be able to contribute some code!

**Comment by CiiDyR** [comment]
This would be awesome! Currently when upgrading our immutable infrastructure the nodes get kicked from the cluster, without properly draining them.
This causes some issues as it takes a while before the cluster notices and reschedules them on other nodes.
It would be amazing if the nodes would be drained before being removed

**Comment by rawmind0** [comment]
Hi @aledegano , have you consider using [upgrade_strategy](https://github.com/rancher/terraform-provider-rke/blob/master/docs/resources/cluster.md#upgrade_strategy) ??

**Comment by rawmind0** [comment]
Please, reopen the issue if required.
