### ISSUE TITLE
[Question] does nodes.address argument have to be an IP ? Is a fqdn an allowed value ? 

### ISSUE THREAD

**Issue by jehutyy** [rancher/terraform-provider-rke#291]
I would like to provide fqdn instead of an IP in the same fashion as it's done in a  `cluster.yml` configuration file.

I'm trying to do so but I keep getting an error `Host [fqdn] is not able to connect to [another-fqdn] to the following ports` even though I can manually connect to said port (with netcat for instance).

**Comment by rawmind0** [comment]
The provider is following the same `cluster.yml` behaviour, so if IP may be provided at `cluster.yml` instead of fqdn, should work here in the same way. Please, check if your networks rules allow communication and if services are up and running to allow connections.
