### ISSUE TITLE
It's still not possible to change node order safely

### ISSUE THREAD

**Issue by luminiscence** [rancher/terraform-provider-rke#293]
I checked and can confirm that issue explained in [ticket](https://github.com/rancher/terraform-provider-rke/issues/229) is still actual. Node order in nodes collection matters and, when I remove node from the middle of a list, provider thinks that last node was removed and all others renamed:
![image](https://user-images.githubusercontent.com/15375180/114048713-02e50c80-98b5-11eb-865c-21d4eca48b22.png)
Provider version I've tried to use is 1.2.1 and it definitely must contain changes, implemented in Aug 2020.

**Comment by rawmind0** [comment]
The list is properly shifted, as shown in the message you attached. NOT all the nodes are renamed, what was `node1` becomes `node2`,  provider is just adjusting node position in the list. This is the expected behaviour

**Comment by luminiscence** [comment]
okay, it's a bit confusing, because plan is not empty even if I just reorder nodes, but terraform apply does the right thing. Thank you and sorry for disturbing.
