### ISSUE TITLE
Support PGP encryption of private keys

### ISSUE THREAD

**Issue by jorhett** [rancher/terraform-provider-rke#297]
Fixing leakage of private keys in #89 doesn't much matter, when anyone who could have seen the leaked value could also do `terraform state` ...any number of choices... and get the values in plaintext. 

When the rancher module outputs are necessary for dev teams who you do not want to access these keys, you can't simply lock the terraform state bucket from their eyes. The workaround most resources have implemented is PGP encryption of insecure values, so that a person can retrieve most of the state but not decode the sensitive values 
  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key#pgp_key
  
Please add this feature so that rancher module outputs can be used by dev teams without being able to decrypt the sensitive values.

**Comment by rawmind0** [comment]
This is not recommended fro hashicrop, https://www.terraform.io/plugin/sdkv2/best-practices/sensitive-state#don-t-encrypt-state

**Comment by jorhett** [comment]
@rawmind0 so how do you solve the problem that dev teams can't use the module outputs without having keys to the entire kingdom?

I don't have a problem with you saying "not this way" but there needs to be a solution other than "no security distinction is possible"
