### ISSUE TITLE
Modifying vsphere_cloud_provider.workspace.folder has no apparent effect on the running cluster

### ISSUE THREAD

**Issue by rgl** [rancher/terraform-provider-rke#306]
I've modified the `vsphere_cloud_provider.workspace.folder` property but it had no effect on the running cluster.

This is the relevant configuration that I'm using:

```hcl
resource "rke_cluster" "example" {
...
  cloud_provider {
    vsphere_cloud_provider {
...
      workspace {
...
        folder = "vm/new-folder-name"
      }
    }
  }
}
```

To reproduce:

1. create a new rke cluster with a folder set to a non-existing folder, say, "vm/folder-name"
2. create a test StorageClass and test PVC
3. do a `kubectl describe pvc` and notice its failing due to ` Failed to provision volume with StorageClass "test": folder 'vm/folder-name' not found`.
4. modify the hcl vsphere_cloud_provider.workspace.folder to an existing folder
5. do a `terraform plan/apply`
6. observe that nothing actually changed in the terraform plan, neither it was applied to the rke cluster configuration. as such, the problem at 3 still happens.

I'm creating the test storageclass and PVC as:

```bash
# create a test StorageClass.
kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: $TF_VAR_vsphere_datastore
  diskformat: thin
  fstype: ext4
EOF
kubectl get storageclass
# create a test PersistentVolumeClaim.
kubectl apply -f - <<'EOF'
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  storageClassName: test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
EOF
# show the PVC status.
# NB this must not show any error or pending state.
kubectl describe pvc
```

Please note that recreating the StorageClass or PVC did not help; so it seems the workspace folder is not being updated at all by the rke provider.

I'm using the terraform `rancher/rke` provider `1.2.3` to launch a `v1.20.8-rancher1-1` kubernetes and terraform `1.0.4`.

PS: I've published the full example at https://github.com/rgl/terraform-rke-vsphere-cloud-provider-example.

**Comment by rawmind0** [comment]
Not a big expert on vsphere, but `workspace.folder` seems not affecting datastore folder, just VMs folder, https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/#workspace , https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#supported-parameters

Have you tried specifying `workspace.default-datastore` or the full datastore path at storage class.

**Comment by rgl** [comment]
@rawmind0, I'm not sure I understood your suggestion. `workspace.folder` is not a datastore, its a VM folder, so I'm not following why modifying `workspace.default-datastore` would change anything.

Please note that when I set `workspace.folder` to a folder that exists from the get-go, everything works fine. This issue is about modifying `workspace.folder` after the initial cluster creation.

**Comment by rawmind0** [comment]
I understood from your message that you are having issues creating PVs, due to vsphere is not finding the datastore path `Failed to provision volume with StorageClass "test": folder 'vm/folder-name' not found` . May be i misunderstood your message.

Anyway, same config is working fine if you just use rke beside the tf provider??

**Comment by rgl** [comment]
Thank you for mentioning the rke_state. It allowed me to see that in fact things are being changed.

I must have forgotten to do a terraform plan/apply, because I cannot reproduce what I describe in this issue anymore. I can now see that with a non-exiting folder the pvc failed to be created, I then modify the workspace to a existing folder, and the pvc is successfully created soon after.

I'm glad that this was a problem from my side, but I'm sorry for wasting your time... :-(
