### ISSUE TITLE
Unable to fully configure ingress controller

### ISSUE THREAD

**Issue by rkh-hash** [rancher/terraform-provider-rke#307]
Hi everyone,

I want to change the default network mode of the NGINX ingress controller as explained in the RKE documentation:

https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-network-options

Do I can reproduce this configuration with this RKE terraform provider ? How I can change the network_mode to `hostPort` ?

I'm using the version `v1.2.2`.

Thanks.

**Comment by rawmind0** [comment]
As per https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#ingress, `network_mode` argument is not yet supported.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rke/pull/323 to add this feature

**Comment by rawmind0** [comment]
Feature included at tfp v1.2.5
