### ISSUE TITLE
Logfile not created

### ISSUE THREAD

**Issue by pwurbs** [rancher/terraform-provider-rke#320]
Version: 1.2.4

Provider settings:
```
provider "rke" {
  alias = "rke"
  debug = true
  log_file = "rke_debug.log"
}
```

Issue: 
I would expect that in the working directory the logfile is created, but it isn't there.

It's my actual goal to see the RKE output the same way as rke were performed manually at the target host. 
But using the RKE terraform provider, I could not find any source for such output. 
Where can i see, what RKE actually did at the target system?

**Comment by rawmind0** [comment]
As you are using provider alias, are you properly defining the provider argument in your rke resources?? `provider = "rke.rke"`

**Comment by pwurbs** [comment]
Thanks. This was the root cause...
