### ISSUE TITLE
Add support for enable_cri_dockerd option

### ISSUE THREAD

**Issue by tsde** [rancher/terraform-provider-rke#325]
Hello,

Can you please add support for the `enable_cri_dockerd` option ? This will be required for future version of Kubernetes for people still using docker as their runtime. It can already be enabled if you use Kubernetes 1.21 as stated in RKE documentation:
```
# Enable running cri-dockerd
# Up to Kubernetes 1.23, kubelet contained code called dockershim 
# to support Docker runtime. The replacement is called cri-dockerd 
# and should be enabled if you want to keep using Docker as your
# container runtime
# Only available to enable in Kubernetes 1.21 and higher
enable_cri_dockerd: true
```

Thank you

**Comment by annablender** [comment]
See test plan for https://github.com/rancher/terraform-provider-rke/issues/342 -> https://github.com/rancher/terraform-provider-rke/issues/342#issuecomment-1147659479.

**Comment by Josh-Diamond** [comment]
Tested and validated as part of related issue #342 ;
Results found [here](https://github.com/rancher/terraform-provider-rke/issues/342#issuecomment-1175362878)
