### ISSUE TITLE
[Feature request] Support RKE 1.3.7 (or newer)

### ISSUE THREAD

**Issue by ttk** [rancher/terraform-provider-rke#328]
The [latest version](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.3.0) of this terraform provider supports RKE 1.3.3.

It would be great to have support for [RKE 1.3.7](https://github.com/rancher/rke/releases/tag/v1.3.7) as there are several improvements and it will allow our team to start testing support for Ubuntu 22.04 (or Debian 11) which requires the fix for updated iptables > 1.8.5.

**Comment by waldner** [comment]
Yes please.

**Comment by hutm** [comment]
what is the process of updating this repo to support the latest RKE release? Is it driven by community or by Rancher repo maintainers ? @rawmind0 , you've released the previous version. Could you please share your opinion here?

**Comment by holtakj** [comment]
this is really annoying. if somebody used this provider to setup RKE with kubernetes 1.22 then he can`t upgrade easily and might fall into this

 https://forums.rancher.com/t/rancher-kubernetes-distributions-and-etcd-3-5-updates/37485

you should release a new version of the provider with every new RKE version or make the RKE version configurable at least for a range of versions of RKEs.

**Comment by a-blender** [comment]
@ttk Apologies for overlooking this issue! The latest version of the provider https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.2 now supports RKE 1.4.6.
