### ISSUE TITLE
Release v1.3.1 is not available in terraform registry

### ISSUE THREAD

**Issue by bitnik** [rancher/terraform-provider-rke#346]
[Release v1.3.1](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.3.1) is not available in terraform registry. There the latest avaible version is 1.3.0: https://registry.terraform.io/providers/rancher/rke/

**Comment by snasovich** [comment]
Thank you for reporting this issue. We're aware that the latest release did not sync to TF registry and have a ticket open with TF/Hashicorp to resolve this.

**Comment by nissimuseri** [comment]
Hi @snasovich !
Is there something new about this issue from Hashicorp side?
It will be fixed soon?

**Comment by snasovich** [comment]
@nissimuseri , unfortunately I still don't have an ETA on this yet.

**Comment by Brianalmeida** [comment]
@snasovich, I just created a Jira for this.

**Comment by dnoland1** [comment]
> We're aware that the latest release did not sync to TF registry and have a ticket open with TF/Hashicorp to resolve this. Moving to "Blocked" due to external block.

@snasovich Is there a link you can share for the tf/hashicorp ticket?

**Comment by snasovich** [comment]
@dnoland1 , EIO team was able to help with manually publishing the release - it should be available now: https://registry.terraform.io/providers/suse-rancher/rke/1.3.1

Closing this issue.
