### ISSUE TITLE
Version 1.3.2 in not available in registry.terraform.io/

### ISSUE THREAD

**Issue by fibiworks** [rancher/terraform-provider-rke#352]
In registry.terraform.io the version 1.3.2 is not visible, as latest version is there only 1.3.1

See
https://registry.terraform.io/providers/rancher/rke/

![image](https://user-images.githubusercontent.com/80623382/181206716-19d9b038-2e61-4caa-a6ec-7c4fab597505.png)

**Comment by jiaqiluo** [comment]
Thanks for reporting this issue.  
We just got it fixed now!  see https://registry.terraform.io/providers/rancher/rke/1.3.2

**Comment by fibiworks** [comment]
thanks a lot
