### ISSUE TITLE
Support k8s 1.24

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/terraform-provider-rke#354]
`terraform-provider-rke` 1.3.2 embeds rke `v1.3.11` which does not support k8s 1.24. 

Once RKE `v1.3.13` is released, a new version of `terraform-provider-rke` will need to be released to test k8s 1.24 support

**Comment by annablender** [comment]
My plan here is the following

- Submit a PR to update the tf rke provider to embed rke 1.3.13 (latest version)
- Release the tf rke provider 1.3.3
- Smoke test provisioning an RKE cluster with the tf rke provider and k8s 1.24
- Add a test template for QA
- Move to test

**Comment by annablender** [comment]
Smoke test is verified on rancher `v2.6-head.`

Test steps
- Provision an RKE cluster on 2 AWS EC2 nodes with kubernetes 1.24 (enable_cri_dockerd = true)
- Verify the cluster comes up successfully
- Verify I can access the cluster via kubectl
- Import the cluster into rancher
- Verify the cluster comes up active

**More detail**

config.tf
```
# Use the rancher/rke Terraform provider
terraform {
  required_providers {
    rke = {
      source = "terraform.example.com/local/rke"
      version = "1.3.2"
    }
  }
}

# Configure RKE provider
provider "rke" {
  log_file = "rke_debug.log"
}

# Create a new RKE cluster using config yaml
resource "rke_cluster" "foo" {
  enable_cri_dockerd = true
  kubernetes_version = "v1.24.2-rancher1-1"
  nodes {
    address = "3.15.161.143"
    internal_address = "172.31.20.206"
    user = "ec2-user"
    role = ["etcd", "controlplane", "worker"]
  }
  nodes {
    address = "18.218.215.197"
    internal_address = "172.31.29.110"
    user = "ec2-user"
    role = ["etcd", "controlplane", "worker"]
  }
  services {
    kubelet {
      image = "rancher/hyperkube:v1.24.2-rancher1"
      extra_env = ["HTTP_PROXY = http://test_proxy", "NO_PROXY = true"]
    }
  }
  ssh_key_path = "~/Downloads/ablender-rke.pem"
}
```

* Run `terraform init`
* Run `terraform apply`
* SSH into one/both of your EC2 nodes and verify docker containers are running and healthy

![image](https://user-images.githubusercontent.com/12955547/187302626-f180a70c-f015-4ab7-b4f5-380ebd565886.png)

* Extract the kubeconfig from your `terraform.tfstate` using [this script](https://gist.github.com/jakefhyde/5e144a35273703eb2191030a1f3d62fa)

* Run the rancher cmd to import a generic cluster
* Verify the cluster comes up active

![image](https://user-images.githubusercontent.com/12955547/187302684-8457f9fc-d220-4f4d-8844-c154e201786f.png)

**Comment by annablender** [comment]
## Testing template

#### Root cause

Release a version of the terraform rke provider that supports provisioning RKE clusters with kubernetes 1.24.
 
#### What was fixed, or what changes have occurred

In the tf rke provider...
- rke updated to v1.3.13 (which supports kubernetes 1.24)
- go client and dependencies updated

#### Areas or cases that should be tested

[Test plan](https://github.com/rancher/terraform-provider-rke/issues/354#issuecomment-1230883523)

#### What areas could experience regressions ?

NA
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
Test Plan:

Repeat the following steps for:
a) Single-node; all-roles
b) 3-node; individual roles - [ 1 etcd, 1 cp, 1 wkr ]

1. Provision a RKE cluster on AWS EC2 nodes with kubernetes 1.24 + `enable_cri_dockerd = true`, using TF rke provider
2. Verify the cluster provisions successfully
3. Verify cluster is accessible via kubectl
4. Import the cluster into rancher (v2.6-head)
5. Verify the cluster comes up active

**Comment by annablender** [comment]
@Josh-Diamond I resolved the ephemeral storage issue by provisioning by EC2 nodes with 20GB disk size. Updated test plan https://github.com/rancher/terraform-provider-rke/issues/354#issuecomment-1230883523. I heard qa uses 50GB so you shouldn't run into evicted pods

**Comment by annablender** [comment]
Terraform rke provider [v1.3.3](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.3.3) is released! It's available on the [terraform registry](https://registry.terraform.io/providers/rancher/rke/latest/docs).

**Comment by Josh-Diamond** [comment]
Ticket #354 - Test Results

With [tf/rancher/rke provider](https://registry.terraform.io/providers/rancher/rke/latest) v1.3.3:

3-node cluster [1 etcd, 1 cp, 1 wkr]:
1. Provision RKE cluster w/ EC2 nodes and kubernetes v1.24; set `enable_cri_dockerd = true`
2. Verified - cluster successfully provisions
3. Set tf output to display kube_config_yaml. - [ if you already created cluster, run `terraform refresh` after adding output to see it available ]
4. Verified - cluster is accessible via kubectl
5. Import cluster into rancher on `v2.6-595fc121cdf4f790bf953408faedc9ddb5d61c30-head`
6. Verified - cluster successfully imports + is active

main.tf
```tf
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.3.3"
    }
  }
}

provider "rke" {
  # Configuration options
}

# Create a new RKE cluster using config yaml
resource "rke_cluster" "rke_cluster" {
  enable_cri_dockerd = true
  kubernetes_version = "v1.24.2-rancher1-1"
  ssh_key_path = "</path/to/key>"

  cluster_yaml = file("cluster.yaml")
}

output "kube_config" {
  value = rke_cluster.rke_cluster.kube_config_yaml
  sensitive = true
}
```

Screenshot - Step 6
<img width="1452" alt="Screen Shot 2022-08-30 at 4 30 27 PM" src="https://user-images.githubusercontent.com/46494969/187561316-31f7ad0f-4db3-404c-a6bd-ff31d05a3af7.png">

---

Single-node all-roles cluster:
1. Provision RKE cluster w/ EC2 nodes and kubernetes v1.24; set `enable_cri_dockerd = true`
2. Verified - cluster successfully provisions
3. Set tf output to display kube_config_yaml. - [ if you already created cluster, run `terraform refresh` after adding output to see it available ]
4. Verified - cluster is accessible via kubectl
5. Import cluster into rancher on `v2.6-595fc121cdf4f790bf953408faedc9ddb5d61c30-head`
6. Verified - cluster successfully imports + is active

Screenshot - Step 6
<img width="1469" alt="Screen Shot 2022-08-30 at 5 06 39 PM" src="https://user-images.githubusercontent.com/46494969/187564745-516b6c23-744e-4626-bf47-bd1efc9645d9.png">
