### ISSUE TITLE
Cannot create a 1.24.2 cluster with rke 1.3.3

### ISSUE THREAD

**Issue by rgl** [rancher/terraform-provider-rke#359]
Cannot create a 1.24.2 cluster with rke 1.3.3.

It can create a 1.23.8 cluster, but modifying the code to just to switch the version as https://github.com/rgl/terraform-libvirt-rke-example/compare/main...upgrade-to-k8s-1.24, it fails with:

```
Failed running cluster err:[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [10.17.3.10]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: ]
```

The logs are at:

[rke.log](https://github.com/rancher/terraform-provider-rke/files/9541049/rke.log)

The last lines of the kubelet logs were:

```plain
0910 18:40:46.931015   37140 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
I0910 18:40:46.931112   37140 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
I0910 18:40:46.931184   37140 manager.go:141] "Creating Device Plugin manager" path="/var/lib/kubelet/device-plugins/kubelet.sock"
I0910 18:40:46.931278   37140 state_mem.go:36] "Initialized new in-memory state store"
I0910 18:40:46.931534   37140 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat="" fullURLFormat="unix://"
W0910 18:40:46.931994   37140 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix: missing address". Reconnecting...
Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address"

```

**Comment by git-ival** [comment]
> Cannot create a 1.24.2 cluster with rke 1.3.3.
> 
> It can create a 1.23.8 cluster, but modifying the code to just to switch the version as [rgl/terraform-libvirt-rke-example@main...upgrade-to-k8s-1.24](https://github.com/rgl/terraform-libvirt-rke-example/compare/main...upgrade-to-k8s-1.24), it fails with:
> 
> ```
> Failed running cluster err:[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [10.17.3.10]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: ]
> ```
> 
> The logs are at:
> 
> [rke.log](https://github.com/rancher/terraform-provider-rke/files/9541049/rke.log)
> 
> The last lines of the kubelet logs were:
> 
> ```
> 0910 18:40:46.931015   37140 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
> I0910 18:40:46.931112   37140 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
> I0910 18:40:46.931184   37140 manager.go:141] "Creating Device Plugin manager" path="/var/lib/kubelet/device-plugins/kubelet.sock"
> I0910 18:40:46.931278   37140 state_mem.go:36] "Initialized new in-memory state store"
> I0910 18:40:46.931534   37140 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat="" fullURLFormat="unix://"
> W0910 18:40:46.931994   37140 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix: missing address". Reconnecting...
> Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address"
> ```

@rgl I looked into your terraform module and it looks like you do not have `enable_cri_dockerd = true` set properly, this is required for 1.24.x clusters. See the release notes for [rke 1.3.13](https://github.com/rancher/rke/releases/tag/v1.3.13), the provider does not automatically set this to true since that would effect all non-1.24.x clusters.

**Comment by rgl** [comment]
That did the trick! Thank You!
