### ISSUE TITLE
Please give a status update on a RKE2 provider for Terraform

### ISSUE THREAD

**Issue by erSitzt** [rancher/terraform-provider-rke#361]
Hi,

there have been multiple issues on this topic, with hints to a coming RKE2-provider for Terraform

#284
#271

And even here
https://github.com/rancher/rke2/issues/1676

Can you please give a status on this ? Is there something in the works ?

**Comment by raelix** [comment]
any updates on this?

**Comment by jakefhyde** [comment]
The issue is being tracked here: https://github.com/rancher/rke2/issues/4322.

**Comment by pneigel-ca** [comment]
@jakefhyde The code proposed seems like modules to install and configure RKE2 and dependent infrastructure, not necessarily creating a Terraform provider [similar to the one for RKE1](https://github.com/rancher/terraform-provider-rke). Is there a plan to create a provider?
