### ISSUE TITLE
Update RKE Terraform Provider with Newest RKE version 1.3.15

### ISSUE THREAD

**Issue by Brianalmeida** [rancher/terraform-provider-rke#364]
Creating this issue to request a new RKE TF provider release to address [this addon issue in RKE](https://github.com/rancher/rancher/issues/38876) and make the default image the latest release of RKE (v1.3.15).

**Comment by annablender** [comment]
Tested on terraform rke provider with rke updated locally to `v1.3.15`

Repro steps
* Provision 2 AWS EC2 nodes for an rke cluster
* Use terraform to provision an rke v1.3.15 cluster on the nodes (I used kubernetes version v1.24.2. The default for this rke version is v1.24.4 so would be good for QA to verify that version as well)
* Verify cluster is healthy

![image](https://user-images.githubusercontent.com/12955547/198132176-199e16f1-ceeb-45d4-a151-f052788d7855.png)

<img width="727" alt="image" src="https://user-images.githubusercontent.com/12955547/198132268-27a3b31e-eaec-4d6e-9563-a4ae07a0fb81.png">

**Comment by annablender** [comment]
Terraform RKE provider v1.3.4 is now released on [the registry](https://registry.terraform.io/providers/rancher/rke/latest), using with default image RKE v1.3.15.

**Comment by Brianalmeida** [comment]
@annablender Thank you 

I believe we can go ahead and close this issue now.
