### ISSUE TITLE
Please create a new release for RKE Release v1.4.1

### ISSUE THREAD

**Issue by Aly-ona** [rancher/terraform-provider-rke#367]
Please create a new release for https://github.com/rancher/rke/releases/tag/v1.4.1

There were issues with the rke 3.1.15: https://github.com/rancher/rke/issues/2709, which get resolved in rke 1.4.1
Please update the terraform provider release. This is affecting our production rancher.

Thank you and kind regards,
Olena

SURE-5931

**Comment by dje4om** [comment]
Hi, 

PR done, waiting for Suse/Rancher review : https://github.com/rancher/terraform-provider-rke/pull/368

**Comment by lots0logs** [comment]
@annablender What's the status of this?

**Comment by lucagouty** [comment]
hi guys, any update on this one? without it we're stuck on k8s v1.24.4

**Comment by Troyhy** [comment]
Any update on this?

**Comment by enrico9034** [comment]
Hi, any update?

**Comment by lots0logs** [comment]
@kinarashah @superseb @prachidamle

**Comment by a-blender** [comment]
PR https://github.com/rancher/terraform-provider-rke/pull/368 has been reviewed and merged! Please wait for provider release v1.3.5 to be available

**Comment by a-blender** [comment]
We have decided to call the release v1.4.0 because it packages RKE v1.4.1 and these lines are loosely aligned by minor version. [TFP rke v1.4.0](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.0) is now released.

**Comment by a-blender** [comment]
QA, please refer to https://github.com/rancher/terraform-provider-rke/issues/371 for testing

**Comment by snasovich** [comment]
Closing as this is superseded by https://github.com/rancher/terraform-provider-rke/issues/371
