### ISSUE TITLE
Create a release for RKE 1.4.2

### ISSUE THREAD

**Issue by bkonick** [rancher/terraform-provider-rke#371]
My team is waiting for this particular release to fix a long-standing AWS bug. https://github.com/rancher/rke/releases/tag/v1.4.2

Can we get a release that includes RKE >= 1.4.2

**Comment by hutm** [comment]
+1

**Comment by a-blender** [comment]
@kinarashah and I are working on this now

**Comment by a-blender** [comment]
[TFP rke v1.4.0](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.0) is now released.

**Comment by a-blender** [comment]
We have decided to call the release v1.4.0 because it packages RKE v1.4.1 and these lines are loosely aligned by minor version. [TFP rke v1.4.0](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.0) is now released.

**Comment by bkonick** [comment]
Thanks @a-blender!

When should we expect this to be available in the terraform registry?

**Comment by a-blender** [comment]
Hashicorp _should_ publish the release within 48 hours. It's the weekend, so I'd expect it to be listed on the registry by Tuesday. I've opened an internal issue to ping Hashicorp about it. just in case.
