### ISSUE TITLE
Release TFP RKE with RKE v1.4.3 that pulls in kubernetes cpu fix

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rke#381]
Release the Terraform RKE provider and bundle RKE v1.4.3 which will bundle rancher image `v1.24.10-rancher4-1` with the Kubernetes cpu fix when it is available.

SURE-5282

**Comment by sowmyav27** [comment]
@Sahota1225 Can you confirm if this needs any QA validations?

**Comment by a-blender** [comment]
@sowmyav27 No QA validations needed.
