### ISSUE TITLE
[Backport v1.3] Update terraform-plugin-sdk to v2

### ISSUE THREAD

**Issue by jakefhyde** [rancher/terraform-provider-rke#390]
Original Issue: https://github.com/rancher/terraform-provider-rke/issues/353

The provider currently uses github.com/hashicorp/terraform-plugin-sdk@v1.17.2. v2 provides noticeable improvements, most notably the ability to debug the provider from within an IDE.

**Comment by Josh-Diamond** [comment]
Ticket #390 - Test Results - ✅ 
---

With tfp-rke `v1.3.5`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE cluster w/ k8s `v1.23.16-rancher2-1` | ✅ |
| 2. | Using cluster from Scenario 1, upgrade k8s version to `v1.24.10-rancher4-1` | ✅ |
| 3. | Using cluster from Scenario 2, add an additional worker node to the cluster | ✅ |

---

Scenario 1a -
1. Using the `main.tf` provided below, provision a downstream RKE cluster using k8s `v1.23.16-rancher2-1`
```terraform
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.3.5"
    }
  }
}

provider "rke" {
  # Configuration options
}


resource "rke_cluster" "rke_cluster" {
  kubernetes_version = "v1.23.16-rancher2-1"
  enable_cri_dockerd = true
  nodes {
    address = "<REDACTED>"
    user = "ubuntu"
    role = ["etcd", "controlplane", "worker"]
    ssh_key = file("<REDACTED>")
  }
  services {
    kube_api {
      pod_security_policy = false
    }
  }
}
```
2. Verified - cluster successfully provisions; as expected

---

Scenario 2 -
1. Using same env + cluster from Scenario 1, upgrade the cluster's k8s version by running the following `main.tf` file
```terraform
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.3.5"
    }
  }
}

provider "rke" {
  # Configuration options
}


resource "rke_cluster" "rke_cluster" {
  kubernetes_version = "v1.24.10-rancher4-1"
  enable_cri_dockerd = true
  nodes {
    address = "<REDACTED>"
    user = "ubuntu"
    role = ["etcd", "controlplane", "worker"]
    ssh_key = file("<REDACTED>")
  }
  services {
    kube_api {
      pod_security_policy = false
    }
  }
}
```
2. Verified - cluster successfully upgrades k8s version; as expected

---

Scenario 3 -
1. Using same env + cluster as Scenario 2, add an additional worker node to the cluster by running the following `main.tf` file
```terraform
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.3.5"
    }
  }
}

provider "rke" {
  # Configuration options
}


resource "rke_cluster" "rke_cluster" {
  kubernetes_version = "v1.24.10-rancher4-1"
  enable_cri_dockerd = true
  nodes {
    address = "<REDACTED>"
    user = "ubuntu"
    role = ["etcd", "controlplane", "worker"]
    ssh_key = file("<REDACTED>")
  }
  nodes {
    address = "<REDACTED>"
    user = "ubuntu"
    role = ["worker"]
    ssh_key = file("<REDACTED>")
  }
  services {
    kube_api {
      pod_security_policy = false
    }
  }
}
```
