### ISSUE TITLE
Upgrade kubernetes-release GCS bucket to dl.k8s.io for downloading kubectl

### ISSUE THREAD

**Issue by superseb** [rancher/terraform-provider-rke#421]
Preparing for GCS bucket deprecation at some point (https://github.com/kubernetes/k8s.io/issues/2396)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream cluster via TFP RKE|
|2|As a standard user, provision a downstream cluster via TFP RKE, upgrade the downstream cluster to highest K8s version|

**Comment by markusewalker** [comment]
Validated this against `v1.4.3-rc2`. See details below:

**ENVIRONMENT DETAILS**
- TFP-RKE version: `v1.4.3-rc2`

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Provision a downstream cluster via TFP RKE|:white_check_mark:|
|2|Provision a downstream cluster via TFP RKE, upgrade the cluster to highest K8s version|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Navigated to a client machine with Terraform and kubectl installed to install my cluster (3 etcd, 3 cp, 3 worker).
2. Created a main.tf file with the following configuration:
```
terraform {
  required_providers {
    rke = {
      source  = "rancher/rke"
      version = "1.4.3-rc2"
    }
  }
}
provider "rke" {
  log_file = "rke_debug.log"
}
resource "rke_cluster" "main" {
  nodes {
    address = "..."
    user    = "ec2-user"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = file("<retracted>")
  }
  enable_cri_dockerd = true
}
resource "rke_cluster" "worker1" {
  nodes {
    address = "..."
    user    = "ec2-user"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = file("<retracted>")
  }
  enable_cri_dockerd = true
}
resource "rke_cluster" "worker2" {
  nodes {
    address = "..."
    user    = "ec2-user"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = file("/<retracted>")
  }
  enable_cri_dockerd = true
}
```
3. Ran terraform apply --auto-approve; validated that the cluster was successfully created;
```
> kubectl get nodes
NAME             STATUS   ROLES                      AGE     VERSION
<retracted>  Ready    controlplane,etcd,worker   2m51s   v1.26.9
<retracted>    Ready    controlplane,etcd,worker   2m51s   v1.26.9
<retracted>    Ready    controlplane,etcd,worker   2m50s   v1.26.9
```

_______

**Scenario 2**
1. Repeated scenario 1, but ensured that I provisioned a downstream cluster with added field `kubernetes_version` set to `v1.25.14-rancher1-1`:
```
> kubectl get nodes
NAME             STATUS   ROLES                      AGE    VERSION
<retracted>   Ready    controlplane,etcd,worker   110s   v1.25.14
<retracted>   Ready    controlplane,etcd,worker   110s   v1.25.14
<retracted>    Ready    controlplane,etcd,worker   110s   v1.25.14
```
2. Updated the `main.tf` to have `v1.26.9-rancher1-1` as the latest K8s version; ran `terraform apply --auto-approve` with successful results:
```
> kubectl get nodes
NAME             STATUS   ROLES                      AGE     VERSION
<retracted>   Ready    controlplane,etcd,worker   6m10s   v1.26.9
<retracted>    Ready    controlplane,etcd,worker   6m10s   v1.26.9
<retracted>    Ready    controlplane,etcd,worker   6m10s   v1.26.9
```
