### ISSUE TITLE
Fix CVE dependabot from updating deps to earlier RC versions

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rke#425]
The TFP rke provider (or just general?) dependabot is updating deps to earlier RC versions which will affect release. This was seen yesterday in 2 separate PRs. Example: https://github.com/rancher/terraform-provider-rke/pull/424#discussion_r1375030997, https://github.com/rancher/terraform-provider-rke/pull/417#discussion_r1375119228.

**Comment by superseb** [comment]
@a-blender  What is the ask here? We don't operate dependabot, you can file issues [here](https://github.com/dependabot/dependabot-core/issues).

You can switch to Renovate if you want, it can be deployed using [this workflow](https://github.com/rancher/renovate-config/actions/workflows/renovate-deploy.yml). Make sure to disable dependabot in that case.

Let me know if you need any help on this.
