### ISSUE TITLE
Update RKE to latest v1.4.11

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rke#429]
https://github.com/rancher/rke/releases/tag/v1.4.11

**Comment by a-blender** [comment]
## QA Test Template

Provision an RKE cluster on EC2 nodes (or whatever is easiest) for each new k8s version `v1.26.9-rancher1-1` and `v1.25.14-rancher1-1`. Verify that both clusters come up active and both are healthy.

**Comment by Josh-Diamond** [comment]
Ticket #429 - Test Results - ✅ 
---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Using tfp-rke `v1.4.11-rc2`, provision a standalone RKE w/ k8s `v1.26.9-rancher1-1` | ✅ |
| 2. | Using tfp-rke `v1.4.11-rc2`, provision a standalone RKE w/ k8s `v1.25.14-rancher1-1` | ✅ |

Testing was conducted with the following files:

`cluster.yml`
```yaml
nodes:
  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]
```

`main.tf`
```terraform
terraform {
  required_providers {
    rke = {
      source = "terraform.local/local/rke"
      version = "1.4.3-rc2"
    }
  }
}

provider "rke" {
  # Configuration options
}



resource "rke_cluster" "foo" {
  cluster_yaml = file("cluster.yml")
  kubernetes_version = "v1.26.9-rancher1-1" # "v1.25.14-rancher1-1"
  enable_cri_dockerd = true
  ssh_key_path = "<REDACTED>"
}
```
`outputs.tf`
```terraform
output "kube_config_yaml" {
  value = rke_cluster.foo.kube_config_yaml
  sensitive = true
}
```
