### ISSUE TITLE
Update RKE to latest

### ISSUE THREAD

**Issue by timursaikaliev** [rancher/terraform-provider-rke#443]
https://github.com/rancher/rke/releases

**Comment by kingnarmer** [comment]
Will be good if provider updated to latest.

**Comment by ajchiarello** [comment]
More specifically, can we upgrade to the 1.5 branch of RKE, so that we can deploy Kubernetes 1.27+? 1.26 is EOL at the end of February 2024. https://kubernetes.io/releases/#release-v1-26

**Comment by raelix** [comment]
any updates on this?

**Comment by enrico9034** [comment]
Sorry any update?

**Comment by jiaqiluo** [comment]
This can be validated with https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.4-rc1
