### ISSUE TITLE
Support RKE1 with K8s 1.28 support

### ISSUE THREAD

**Issue by snasovich** [rancher/terraform-provider-rke#447]
This issue is to track releasing `terraform-provider-rke` v1.5.0 updated to RKE1 release with support for K8s 1.28 (tentatively RKE1 1.5.7)

**Comment by snasovich** [comment]
Blocked as we're waiting for RKE1 1.5.7 release.

**Comment by enrico9034** [comment]
@snasovich do you already test rke 1.5.x? I don't find the full changelog between 1.4.x and 1.5.x

**Comment by snasovich** [comment]
@enrico9034 , apologies for late response. There are already multiple releases of RKE1 1.5.x with the latest one released last week that adds support for K8s 1.28 - https://github.com/rancher/rke/releases/tag/v1.5.7
This issue is to track release of Terraform Provider for RKE1 version 1.5.x based on that RKE1 release.

**Comment by jiaqiluo** [comment]
This issue can be validated with v1.5.0-rc1  https://github.com/rancher/terraform-provider-rke/releases/tag/v1.5.0-rc1

**Comment by Josh-Diamond** [comment]
Ticket #447 - Test Results - ✅ 
---

Validated standalone provisioning of RKE `v1.28.7-rancher1-1`, using TFP-RKE `v1.5.0-rc1` - ✅
