### ISSUE TITLE
[1.6] RKE v1.6.3 support

### ISSUE THREAD

**Issue by kingnarmer** [rancher/terraform-provider-rke#460]
This issue is used to track the effort for supporting RKE v1.6 which the upcoming release is v1.6.3 

--------
Original message: 
Please update terraform-provider-rke to support rke v1.6.0.

**Comment by timursaikaliev** [comment]
@jiaqiluo any updates?

**Comment by jiaqiluo** [comment]
Hi @timursaikaliev, the team is working on getting the linked PR merged, validating the change, and finally cutting a release.

**Comment by jiaqiluo** [comment]
this issue can be validated in [v1.6.0-rc11](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.6.0-rc11)

**Comment by timursaikaliev** [comment]
Can someone please do a validation?

**Comment by timursaikaliev** [comment]
Hi @jiaqiluo
Validated provisioning of **RKE** `v1.30.5-rancher1-1`, using **TFP-RKE** `1.6.0-rc12`:
<img width="369" alt="image" src="https://github.com/user-attachments/assets/b8c77671-91c3-484c-9f89-5a1de37ab7f3">
