### ISSUE TITLE
Add this plugin in terraform registry

### ISSUE THREAD

**Issue by paulobezerr** [rancher/terraform-provider-rke#63]
With this, we dont need to install the plugin manually.
It will be downloaded in `terraform init`

https://registry.terraform.io/github/create

**Comment by yamamoto-febc** [comment]
Hi @paulobezerr, 

Thank you for your suggesting.

Currently, the official providers are moving to being sourced from the Terraform Registry.
However, it doesn't support 3rd providers yet.
(see https://github.com/hashicorp/terraform/issues/15252#issuecomment-444128463)

If it done, we will support it.

**Comment by marioapardo** [comment]
Hi, an option to download the plugin with `terraform init` [adding-provider-source-to-hashicorp-terraform] (https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/)

**Comment by rawmind0** [comment]
Hi @marioapardo , we are already working with hashicorp to add this provider to the terraform registry. 

The one caveat is that Community providers published via the Terraform Registry will only be installable via Terraform 0.13, which beta was just released last week. The tf 0.13 GA release should follow in the next few months.

**Comment by rawmind0** [comment]
RKE provider is already published on terraform registry, https://registry.terraform.io/providers/rancher/rke/latest

Please, reopen issue if needed.
