### ISSUE TITLE
Terraform import

### ISSUE THREAD

**Issue by xbaran** [rancher/terraform-provider-rke#75]
Any chance to provide import functionality?

Now `terraform import rke_cluster.cluster cluster-id-123` return `Error: rke_cluster.cluster (import id: stage): import rke_cluster.cluster (id: stage): resource rke_cluster doesn't support import`

Thanks.

**Comment by yamamoto-febc** [comment]
Hi @xbaran, 

Supporting `import` feature is on our roadmap.
However, I don't have enough time to implements this:cry:, so we have no plans to implement it right now.

PR is always welcome:wink:

**Comment by rawmind0** [comment]
Import support is added on PR #185 . Please, reopen issue if needed
