### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by yamamoto-febc** [rancher/terraform-provider-rke#80]
Versioning of this provider is as follows.

- `v1.x.x`: terraform v0.12+(terraform API version: 5, RKE 0.2+)
- `v0.10+.x`: terraform v0.11(but v0.12 syntax ready, RKE 0.2+)
- `v0.9.x`: terraform v0.11 + RKE 0.1.x(bug fix only)

**Comment by yamamoto-febc** [comment]
Current terraform provider SDK is compatible to both of v0.11 and v0.12.
It is not a major change for this provider, so I think we don't need to use v1.x.x yet.

**Comment by drpebcak** [comment]
This versioning scheme is super confusing.. There is no v1.x.x release that has been updated to use RKE 0.2.4, but the 0.12.1 release which seems to be based off the master branch has it? Which release actually has the most up to date stuff? I want to use terraform 0.12.x and also a new version of RKE (0.2.5 is the latest now, but I think the newest version in this project is 0.2.4).

**Comment by drpebcak** [comment]
is 1.x.x abandoned in favor of 0.10+.x?

**Comment by yamamoto-febc** [comment]
@drpebcak I am sorry to make you feel confused.  

Current versioning policy on this project is:

- `v0.10+`: terraform v0.12 + RKE 0.2.x 
- `v0.9`: terraform v0.11 + RKE 0.1.x(bug fix only)

There are currently no plans to release `v1.x.x`.
(please see [my previous comment](https://github.com/yamamoto-febc/terraform-provider-rke/issues/80#issuecomment-499733810))

And to support RKE v0.2.5 in this project is in progress.
Please wait for #105 to merge.

**Comment by yamamoto-febc** [comment]
`v0.13.0` has been released.
This version is supporting RKE `v0.2.5`.

https://github.com/yamamoto-febc/terraform-provider-rke/releases/tag/0.13.0
