### ISSUE TITLE
Custom certificates support

### ISSUE THREAD

**Issue by jonandernovella** [rancher/terraform-provider-rke#84]
Available as of v0.2.0, RKE supports [using custom certificates](https://rancher.com/docs/rke/latest/en/installation/certs/). Is there any documented example on how to do this with this provider?

Thanks in advance!

**Comment by yamamoto-febc** [comment]
Hi @jonandernovella,

Unfortunately, terraform-provider-rke doesn't support using custom certificates right now.
However, I think it is useful. So I'll try to support it ASAP.

**Comment by jonandernovella** [comment]
@yamamoto-febc Good to hear. Thanks for the rapid response.

Cheers!

**Comment by yamamoto-febc** [comment]
Hi @yanndegat, thank you for the suggestion!

It sounds good:+1:
It seems #87 also can be solved with this design.

**Comment by rawmind0** [comment]
This PR https://github.com/rancher/terraform-provider-rke/pull/172 added support for custom_certs and cert_dir arguments,
