### ISSUE TITLE
Cert rotation for existing cluster

### ISSUE THREAD

**Issue by joncak** [rancher/terraform-provider-rke#87]
Hi, its look like the default certificates in rke last 365 days how we could extend the date ? 
with rke they have `./rke cert rotate` in the latest version.

**Comment by yamamoto-febc** [comment]
Hi @joncak,

Unfortunately, cert rotation is not supported now.  
However, we are planning to support this:+1:.
Please wait for the next version:smile:

**Comment by pbaezab** [comment]
How to help you with this task. You have any document or reference with this?

**Comment by yamamoto-febc** [comment]
@pbaezab 

I plan to support this in the following way.

- Allow the following blocks to specify `min_days_remaining`:  

  - `services_kube_api`
  - `services_kube_controller`
  - `services_scheduler`
  - `services_kubelet`
  - `services_kubeproxy`
  - `services_etcd`

- Get the expiration date of cert at `terraform apply`, judging by comparing with `min_days_remaining`, and rotate it if necessary.

- If `min_days_remmaining` is set to 0, we don't rotate certs.

I don't know yet if it is feasible, but I will try to implement such a way.

**Comment by ion1** [comment]
One option would be to use Terraform's [TLS Provider](https://www.terraform.io/docs/providers/tls/index.html) which does certificate rotation upon `terraform apply` based on the `validity_period_hours` and `early_renewal_hours` arguments.

Having the CA as a Terraform TLS resource could be useful if you want to sign something else with it through Terraform as well.

**Comment by yamamoto-febc** [comment]
@ion1 Thank you for your suggestion.

To use Terraform's TLS Provider looks good. I'm going to try to use it.

**Comment by rawmind0** [comment]
From provider v1.0.0-rc1, [rotate_certificates](https://github.com/rancher/terraform-provider-rke/blob/master/website/docs/r/cluster.html.markdown#rotate_certificates) are supported.

Please, reopen issue if needed
