### ISSUE TITLE
rke_cluster leaks private sshKey on destroy

### ISSUE THREAD

**Issue by invidian** [rancher/terraform-provider-rke#89]
When removing node from the cluster, `terraform plan` prints following output:
```
  ~ rke_cluster.cluster
      kube_config_yaml:       <sensitive> => <computed> (attribute changed)
      nodes_conf.#:           "3" => "2"
      nodes_conf.2:           "{\"address\":\"0.0.0.0\",\"port\":\"22\",\"internalAddress\":\"10.44.0.3\",\"role\":[\"worker\"],\"hostnameOverride\":\"testing-3.local\",\"user\":\"core\",\"sshKey\":\"-----BEGIN RSA PRIVATE KEY-----\\n<deducted>n-----END RSA PRIVATE KEY-----\\n\"}" => ""
```

I think we can just set `nodes_conf` to computed as done with other parameters and then it should be fine.

**Comment by yamamoto-febc** [comment]
Hi @invidian, thank you for reporting!

>I think we can just set nodes_conf to computed as done with other parameters and then it should be fine.

I think so too. I'm going to  fix it.
